/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation';
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization';
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile';
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index';
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId';
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients/new';
import { Route as AuthenticatedClientsClientIdIndexRouteImport } from './routes/_authenticated/clients/$clientId/index';
import { Route as AuthenticatedClientsClientIdDocumentDataRouteImport } from './routes/_authenticated/clients/$clientId/document-data';
import { Route as AuthenticatedClientsClientIdDocumentsRouteImport } from './routes/_authenticated/clients/$clientId/documents';
import { Route as AuthenticatedClientsClientIdEmployeesRouteImport } from './routes/_authenticated/clients/$clientId/employees';
import { Route as AuthenticatedClientsClientIdDocumentsIndexRouteImport } from './routes/_authenticated/clients/$clientId/documents/index';
import { Route as AuthenticatedClientsClientIdDocumentsDocumentIdRouteImport } from './routes/_authenticated/clients/$clientId/documents/$documentId';
import { Route as AuthenticatedClientsClientIdEmployeesIndexRouteImport } from './routes/_authenticated/clients/$clientId/employees/index';
import { Route as AuthenticatedClientsClientIdEmployeesEmployeeIdRouteImport } from './routes/_authenticated/clients/$clientId/employees/$employeeId';
import { Route as AuthenticatedClientsClientIdEmployeesNewRouteImport } from './routes/_authenticated/clients/$clientId/employees/new';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any);
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any);
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any);
const AuthenticatedClientsClientIdIndexRoute =
  AuthenticatedClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentDataRoute =
  AuthenticatedClientsClientIdDocumentDataRouteImport.update({
    id: '/document-data',
    path: '/document-data',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentsRoute =
  AuthenticatedClientsClientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesRoute =
  AuthenticatedClientsClientIdEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentsIndexRoute =
  AuthenticatedClientsClientIdDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentsDocumentIdRoute =
  AuthenticatedClientsClientIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedClientsClientIdDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesIndexRoute =
  AuthenticatedClientsClientIdEmployeesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdEmployeesRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesEmployeeIdRoute =
  AuthenticatedClientsClientIdEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AuthenticatedClientsClientIdEmployeesRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesNewRoute =
  AuthenticatedClientsClientIdEmployeesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedClientsClientIdEmployeesRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/accept-invitation': typeof AcceptInvitationRoute;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/clients': typeof AuthenticatedClientsRouteWithChildren;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/organization': typeof AuthenticatedOrganizationRoute;
  '/profile': typeof AuthenticatedProfileRoute;
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren;
  '/clients/new': typeof AuthenticatedClientsNewRoute;
  '/clients/': typeof AuthenticatedClientsIndexRoute;
  '/clients/$clientId/document-data': typeof AuthenticatedClientsClientIdDocumentDataRoute;
  '/clients/$clientId/documents': typeof AuthenticatedClientsClientIdDocumentsRouteWithChildren;
  '/clients/$clientId/employees': typeof AuthenticatedClientsClientIdEmployeesRouteWithChildren;
  '/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute;
  '/clients/$clientId/documents/$documentId': typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  '/clients/$clientId/employees/$employeeId': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  '/clients/$clientId/employees/new': typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  '/clients/$clientId/documents/': typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
  '/clients/$clientId/employees/': typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/accept-invitation': typeof AcceptInvitationRoute;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/organization': typeof AuthenticatedOrganizationRoute;
  '/profile': typeof AuthenticatedProfileRoute;
  '/clients/new': typeof AuthenticatedClientsNewRoute;
  '/clients': typeof AuthenticatedClientsIndexRoute;
  '/clients/$clientId/document-data': typeof AuthenticatedClientsClientIdDocumentDataRoute;
  '/clients/$clientId': typeof AuthenticatedClientsClientIdIndexRoute;
  '/clients/$clientId/documents/$documentId': typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  '/clients/$clientId/employees/$employeeId': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  '/clients/$clientId/employees/new': typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  '/clients/$clientId/documents': typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
  '/clients/$clientId/employees': typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/accept-invitation': typeof AcceptInvitationRoute;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/_authenticated/organization': typeof AuthenticatedOrganizationRoute;
  '/_authenticated/profile': typeof AuthenticatedProfileRoute;
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren;
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute;
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute;
  '/_authenticated/clients/$clientId/document-data': typeof AuthenticatedClientsClientIdDocumentDataRoute;
  '/_authenticated/clients/$clientId/documents': typeof AuthenticatedClientsClientIdDocumentsRouteWithChildren;
  '/_authenticated/clients/$clientId/employees': typeof AuthenticatedClientsClientIdEmployeesRouteWithChildren;
  '/_authenticated/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute;
  '/_authenticated/clients/$clientId/documents/$documentId': typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  '/_authenticated/clients/$clientId/employees/$employeeId': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  '/_authenticated/clients/$clientId/employees/new': typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  '/_authenticated/clients/$clientId/documents/': typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
  '/_authenticated/clients/$clientId/employees/': typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/clients'
    | '/dashboard'
    | '/organization'
    | '/profile'
    | '/clients/$clientId'
    | '/clients/new'
    | '/clients/'
    | '/clients/$clientId/document-data'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/employees'
    | '/clients/$clientId/'
    | '/clients/$clientId/documents/$documentId'
    | '/clients/$clientId/employees/$employeeId'
    | '/clients/$clientId/employees/new'
    | '/clients/$clientId/documents/'
    | '/clients/$clientId/employees/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/accept-invitation'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/organization'
    | '/profile'
    | '/clients/new'
    | '/clients'
    | '/clients/$clientId/document-data'
    | '/clients/$clientId'
    | '/clients/$clientId/documents/$documentId'
    | '/clients/$clientId/employees/$employeeId'
    | '/clients/$clientId/employees/new'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/employees';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/confirm-email'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/organization'
    | '/_authenticated/profile'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/clients/'
    | '/_authenticated/clients/$clientId/document-data'
    | '/_authenticated/clients/$clientId/documents'
    | '/_authenticated/clients/$clientId/employees'
    | '/_authenticated/clients/$clientId/'
    | '/_authenticated/clients/$clientId/documents/$documentId'
    | '/_authenticated/clients/$clientId/employees/$employeeId'
    | '/_authenticated/clients/$clientId/employees/new'
    | '/_authenticated/clients/$clientId/documents/'
    | '/_authenticated/clients/$clientId/employees/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AcceptInvitationRoute: typeof AcceptInvitationRoute;
  ConfirmEmailRoute: typeof ConfirmEmailRoute;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/accept-invitation': {
      id: '/accept-invitation';
      path: '/accept-invitation';
      fullPath: '/accept-invitation';
      preLoaderRoute: typeof AcceptInvitationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/confirm-email': {
      id: '/confirm-email';
      path: '/confirm-email';
      fullPath: '/confirm-email';
      preLoaderRoute: typeof ConfirmEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding': {
      id: '/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/clients': {
      id: '/_authenticated/clients';
      path: '/clients';
      fullPath: '/clients';
      preLoaderRoute: typeof AuthenticatedClientsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/organization': {
      id: '/_authenticated/organization';
      path: '/organization';
      fullPath: '/organization';
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/profile': {
      id: '/_authenticated/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof AuthenticatedProfileRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/';
      path: '/';
      fullPath: '/clients/';
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsRoute;
    };
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId';
      path: '/$clientId';
      fullPath: '/clients/$clientId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport;
      parentRoute: typeof AuthenticatedClientsRoute;
    };
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new';
      path: '/new';
      fullPath: '/clients/new';
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport;
      parentRoute: typeof AuthenticatedClientsRoute;
    };
    '/_authenticated/clients/$clientId/': {
      id: '/_authenticated/clients/$clientId/';
      path: '/';
      fullPath: '/clients/$clientId/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/document-data': {
      id: '/_authenticated/clients/$clientId/document-data';
      path: '/document-data';
      fullPath: '/clients/$clientId/document-data';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentDataRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/documents': {
      id: '/_authenticated/clients/$clientId/documents';
      path: '/documents';
      fullPath: '/clients/$clientId/documents';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentsRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/employees': {
      id: '/_authenticated/clients/$clientId/employees';
      path: '/employees';
      fullPath: '/clients/$clientId/employees';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/documents/': {
      id: '/_authenticated/clients/$clientId/documents/';
      path: '/';
      fullPath: '/clients/$clientId/documents/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentsIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/documents/$documentId': {
      id: '/_authenticated/clients/$clientId/documents/$documentId';
      path: '/$documentId';
      fullPath: '/clients/$clientId/documents/$documentId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentsDocumentIdRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/employees/': {
      id: '/_authenticated/clients/$clientId/employees/';
      path: '/';
      fullPath: '/clients/$clientId/employees/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdEmployeesRoute;
    };
    '/_authenticated/clients/$clientId/employees/$employeeId': {
      id: '/_authenticated/clients/$clientId/employees/$employeeId';
      path: '/$employeeId';
      fullPath: '/clients/$clientId/employees/$employeeId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdEmployeesRoute;
    };
    '/_authenticated/clients/$clientId/employees/new': {
      id: '/_authenticated/clients/$clientId/employees/new';
      path: '/new';
      fullPath: '/clients/$clientId/employees/new';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesNewRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdEmployeesRoute;
    };
  }
}

interface AuthenticatedClientsClientIdDocumentsRouteChildren {
  AuthenticatedClientsClientIdDocumentsDocumentIdRoute: typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  AuthenticatedClientsClientIdDocumentsIndexRoute: typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
}

const AuthenticatedClientsClientIdDocumentsRouteChildren: AuthenticatedClientsClientIdDocumentsRouteChildren =
  {
    AuthenticatedClientsClientIdDocumentsDocumentIdRoute:
      AuthenticatedClientsClientIdDocumentsDocumentIdRoute,
    AuthenticatedClientsClientIdDocumentsIndexRoute:
      AuthenticatedClientsClientIdDocumentsIndexRoute,
  };

const AuthenticatedClientsClientIdDocumentsRouteWithChildren =
  AuthenticatedClientsClientIdDocumentsRoute._addFileChildren(
    AuthenticatedClientsClientIdDocumentsRouteChildren,
  );

interface AuthenticatedClientsClientIdEmployeesRouteChildren {
  AuthenticatedClientsClientIdEmployeesEmployeeIdRoute: typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  AuthenticatedClientsClientIdEmployeesNewRoute: typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  AuthenticatedClientsClientIdEmployeesIndexRoute: typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
}

const AuthenticatedClientsClientIdEmployeesRouteChildren: AuthenticatedClientsClientIdEmployeesRouteChildren =
  {
    AuthenticatedClientsClientIdEmployeesEmployeeIdRoute:
      AuthenticatedClientsClientIdEmployeesEmployeeIdRoute,
    AuthenticatedClientsClientIdEmployeesNewRoute:
      AuthenticatedClientsClientIdEmployeesNewRoute,
    AuthenticatedClientsClientIdEmployeesIndexRoute:
      AuthenticatedClientsClientIdEmployeesIndexRoute,
  };

const AuthenticatedClientsClientIdEmployeesRouteWithChildren =
  AuthenticatedClientsClientIdEmployeesRoute._addFileChildren(
    AuthenticatedClientsClientIdEmployeesRouteChildren,
  );

interface AuthenticatedClientsClientIdRouteChildren {
  AuthenticatedClientsClientIdDocumentDataRoute: typeof AuthenticatedClientsClientIdDocumentDataRoute;
  AuthenticatedClientsClientIdDocumentsRoute: typeof AuthenticatedClientsClientIdDocumentsRouteWithChildren;
  AuthenticatedClientsClientIdEmployeesRoute: typeof AuthenticatedClientsClientIdEmployeesRouteWithChildren;
  AuthenticatedClientsClientIdIndexRoute: typeof AuthenticatedClientsClientIdIndexRoute;
}

const AuthenticatedClientsClientIdRouteChildren: AuthenticatedClientsClientIdRouteChildren =
  {
    AuthenticatedClientsClientIdDocumentDataRoute:
      AuthenticatedClientsClientIdDocumentDataRoute,
    AuthenticatedClientsClientIdDocumentsRoute:
      AuthenticatedClientsClientIdDocumentsRouteWithChildren,
    AuthenticatedClientsClientIdEmployeesRoute:
      AuthenticatedClientsClientIdEmployeesRouteWithChildren,
    AuthenticatedClientsClientIdIndexRoute:
      AuthenticatedClientsClientIdIndexRoute,
  };

const AuthenticatedClientsClientIdRouteWithChildren =
  AuthenticatedClientsClientIdRoute._addFileChildren(
    AuthenticatedClientsClientIdRouteChildren,
  );

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRouteWithChildren;
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute;
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute;
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute:
    AuthenticatedClientsClientIdRouteWithChildren,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
};

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRoute;
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
