/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as IndexRouteImport } from './routes/index';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation';
import { Route as ConfirmEmailRouteImport } from './routes/confirm-email';
import { Route as ContractRouteImport } from './routes/contract';
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password';
import { Route as LoginRouteImport } from './routes/login';
import { Route as OnboardingRouteImport } from './routes/onboarding';
import { Route as RegisterRouteImport } from './routes/register';
import { Route as ResetPasswordRouteImport } from './routes/reset-password';
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients';
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard';
import { Route as AuthenticatedInstructionsRouteImport } from './routes/_authenticated/instructions';
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads';
import { Route as AuthenticatedOrganizationRouteImport } from './routes/_authenticated/organization';
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile';
import { Route as AuthenticatedRisksRouteImport } from './routes/_authenticated/risks';
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients/index';
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients/$clientId';
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients/new';
import { Route as AuthenticatedInstructionsIndexRouteImport } from './routes/_authenticated/instructions/index';
import { Route as AuthenticatedInstructionsModuleIdRouteImport } from './routes/_authenticated/instructions/$moduleId';
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads/index';
import { Route as AuthenticatedLeadsLeadIdRouteImport } from './routes/_authenticated/leads/$leadId';
import { Route as AuthenticatedLeadsNewRouteImport } from './routes/_authenticated/leads/new';
import { Route as AuthenticatedOrganizationIndexRouteImport } from './routes/_authenticated/organization/index';
import { Route as AuthenticatedOrganizationAuthorizationsRouteImport } from './routes/_authenticated/organization/authorizations';
import { Route as AuthenticatedOrganizationCompanyRouteImport } from './routes/_authenticated/organization/company';
import { Route as AuthenticatedOrganizationTeamRouteImport } from './routes/_authenticated/organization/team';
import { Route as AuthenticatedRisksIndexRouteImport } from './routes/_authenticated/risks/index';
import { Route as AuthenticatedRisksProfileIdRouteImport } from './routes/_authenticated/risks/$profileId';
import { Route as AuthenticatedClientsClientIdIndexRouteImport } from './routes/_authenticated/clients/$clientId/index';
import { Route as AuthenticatedClientsClientIdContactRouteImport } from './routes/_authenticated/clients/$clientId/contact';
import { Route as AuthenticatedClientsClientIdContractRouteImport } from './routes/_authenticated/clients/$clientId/contract';
import { Route as AuthenticatedClientsClientIdDetailsRouteImport } from './routes/_authenticated/clients/$clientId/details';
import { Route as AuthenticatedClientsClientIdDocumentDataRouteImport } from './routes/_authenticated/clients/$clientId/document-data';
import { Route as AuthenticatedClientsClientIdDocumentsRouteImport } from './routes/_authenticated/clients/$clientId/documents';
import { Route as AuthenticatedClientsClientIdEditRouteImport } from './routes/_authenticated/clients/$clientId/edit';
import { Route as AuthenticatedClientsClientIdEmployeesRouteImport } from './routes/_authenticated/clients/$clientId/employees';
import { Route as AuthenticatedClientsClientIdFireSafetyDocumentsRouteImport } from './routes/_authenticated/clients/$clientId/fire-safety-documents';
import { Route as AuthenticatedClientsClientIdJobPositionsRouteImport } from './routes/_authenticated/clients/$clientId/job-positions';
import { Route as AuthenticatedClientsClientIdOtherDocumentsRouteImport } from './routes/_authenticated/clients/$clientId/other-documents';
import { Route as AuthenticatedClientsClientIdTrainingRouteImport } from './routes/_authenticated/clients/$clientId/training';
import { Route as AuthenticatedLeadsLeadIdIndexRouteImport } from './routes/_authenticated/leads/$leadId/index';
import { Route as AuthenticatedLeadsLeadIdContractRouteImport } from './routes/_authenticated/leads/$leadId/contract';
import { Route as AuthenticatedLeadsLeadIdEditRouteImport } from './routes/_authenticated/leads/$leadId/edit';
import { Route as AuthenticatedClientsClientIdContractIndexRouteImport } from './routes/_authenticated/clients/$clientId/contract/index';
import { Route as AuthenticatedClientsClientIdContractEditRouteImport } from './routes/_authenticated/clients/$clientId/contract/edit';
import { Route as AuthenticatedClientsClientIdDocumentsIndexRouteImport } from './routes/_authenticated/clients/$clientId/documents/index';
import { Route as AuthenticatedClientsClientIdDocumentsDocumentIdRouteImport } from './routes/_authenticated/clients/$clientId/documents/$documentId';
import { Route as AuthenticatedClientsClientIdEmployeesIndexRouteImport } from './routes/_authenticated/clients/$clientId/employees/index';
import { Route as AuthenticatedClientsClientIdEmployeesEmployeeIdRouteImport } from './routes/_authenticated/clients/$clientId/employees/$employeeId';
import { Route as AuthenticatedClientsClientIdEmployeesNewRouteImport } from './routes/_authenticated/clients/$clientId/employees/new';
import { Route as AuthenticatedClientsClientIdFireSafetyDocumentsIndexRouteImport } from './routes/_authenticated/clients/$clientId/fire-safety-documents/index';
import { Route as AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRouteImport } from './routes/_authenticated/clients/$clientId/fire-safety-documents/$documentId';
import { Route as AuthenticatedClientsClientIdJobPositionsIndexRouteImport } from './routes/_authenticated/clients/$clientId/job-positions/index';
import { Route as AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteImport } from './routes/_authenticated/clients/$clientId/job-positions/$jobPositionId';
import { Route as AuthenticatedClientsClientIdOtherDocumentsIndexRouteImport } from './routes/_authenticated/clients/$clientId/other-documents/index';
import { Route as AuthenticatedClientsClientIdOtherDocumentsContractRouteImport } from './routes/_authenticated/clients/$clientId/other-documents/contract';
import { Route as AuthenticatedClientsClientIdEmployeesEmployeeIdEditRouteImport } from './routes/_authenticated/clients/$clientId/employees/$employeeId_.edit';
import { Route as AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRouteImport } from './routes/_authenticated/clients/$clientId/job-positions/$jobPositionId/index';
import { Route as AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRouteImport } from './routes/_authenticated/clients/$clientId/job-positions/$jobPositionId/risk-evaluation';
import { Route as AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRouteImport } from './routes/_authenticated/clients/$clientId/job-positions/risk-evaluations.$evaluationId';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfirmEmailRoute = ConfirmEmailRouteImport.update({
  id: '/confirm-email',
  path: '/confirm-email',
  getParentRoute: () => rootRouteImport,
} as any);
const ContractRoute = ContractRouteImport.update({
  id: '/contract',
  path: '/contract',
  getParentRoute: () => rootRouteImport,
} as any);
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedInstructionsRoute =
  AuthenticatedInstructionsRouteImport.update({
    id: '/instructions',
    path: '/instructions',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedOrganizationRoute =
  AuthenticatedOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedRisksRoute = AuthenticatedRisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any);
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any);
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any);
const AuthenticatedInstructionsIndexRoute =
  AuthenticatedInstructionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInstructionsRoute,
  } as any);
const AuthenticatedInstructionsModuleIdRoute =
  AuthenticatedInstructionsModuleIdRouteImport.update({
    id: '/$moduleId',
    path: '/$moduleId',
    getParentRoute: () => AuthenticatedInstructionsRoute,
  } as any);
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any);
const AuthenticatedLeadsLeadIdRoute =
  AuthenticatedLeadsLeadIdRouteImport.update({
    id: '/$leadId',
    path: '/$leadId',
    getParentRoute: () => AuthenticatedLeadsRoute,
  } as any);
const AuthenticatedLeadsNewRoute = AuthenticatedLeadsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any);
const AuthenticatedOrganizationIndexRoute =
  AuthenticatedOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any);
const AuthenticatedOrganizationAuthorizationsRoute =
  AuthenticatedOrganizationAuthorizationsRouteImport.update({
    id: '/authorizations',
    path: '/authorizations',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any);
const AuthenticatedOrganizationCompanyRoute =
  AuthenticatedOrganizationCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any);
const AuthenticatedOrganizationTeamRoute =
  AuthenticatedOrganizationTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedOrganizationRoute,
  } as any);
const AuthenticatedRisksIndexRoute = AuthenticatedRisksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRisksRoute,
} as any);
const AuthenticatedRisksProfileIdRoute =
  AuthenticatedRisksProfileIdRouteImport.update({
    id: '/$profileId',
    path: '/$profileId',
    getParentRoute: () => AuthenticatedRisksRoute,
  } as any);
const AuthenticatedClientsClientIdIndexRoute =
  AuthenticatedClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdContactRoute =
  AuthenticatedClientsClientIdContactRouteImport.update({
    id: '/contact',
    path: '/contact',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdContractRoute =
  AuthenticatedClientsClientIdContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdDetailsRoute =
  AuthenticatedClientsClientIdDetailsRouteImport.update({
    id: '/details',
    path: '/details',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentDataRoute =
  AuthenticatedClientsClientIdDocumentDataRouteImport.update({
    id: '/document-data',
    path: '/document-data',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentsRoute =
  AuthenticatedClientsClientIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdEditRoute =
  AuthenticatedClientsClientIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesRoute =
  AuthenticatedClientsClientIdEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdFireSafetyDocumentsRoute =
  AuthenticatedClientsClientIdFireSafetyDocumentsRouteImport.update({
    id: '/fire-safety-documents',
    path: '/fire-safety-documents',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdJobPositionsRoute =
  AuthenticatedClientsClientIdJobPositionsRouteImport.update({
    id: '/job-positions',
    path: '/job-positions',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdOtherDocumentsRoute =
  AuthenticatedClientsClientIdOtherDocumentsRouteImport.update({
    id: '/other-documents',
    path: '/other-documents',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedClientsClientIdTrainingRoute =
  AuthenticatedClientsClientIdTrainingRouteImport.update({
    id: '/training',
    path: '/training',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any);
const AuthenticatedLeadsLeadIdIndexRoute =
  AuthenticatedLeadsLeadIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLeadsLeadIdRoute,
  } as any);
const AuthenticatedLeadsLeadIdContractRoute =
  AuthenticatedLeadsLeadIdContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => AuthenticatedLeadsLeadIdRoute,
  } as any);
const AuthenticatedLeadsLeadIdEditRoute =
  AuthenticatedLeadsLeadIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedLeadsLeadIdRoute,
  } as any);
const AuthenticatedClientsClientIdContractIndexRoute =
  AuthenticatedClientsClientIdContractIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdContractRoute,
  } as any);
const AuthenticatedClientsClientIdContractEditRoute =
  AuthenticatedClientsClientIdContractEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedClientsClientIdContractRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentsIndexRoute =
  AuthenticatedClientsClientIdDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdDocumentsDocumentIdRoute =
  AuthenticatedClientsClientIdDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedClientsClientIdDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesIndexRoute =
  AuthenticatedClientsClientIdEmployeesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdEmployeesRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesEmployeeIdRoute =
  AuthenticatedClientsClientIdEmployeesEmployeeIdRouteImport.update({
    id: '/$employeeId',
    path: '/$employeeId',
    getParentRoute: () => AuthenticatedClientsClientIdEmployeesRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesNewRoute =
  AuthenticatedClientsClientIdEmployeesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedClientsClientIdEmployeesRoute,
  } as any);
const AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute =
  AuthenticatedClientsClientIdFireSafetyDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdFireSafetyDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute =
  AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRouteImport.update({
    id: '/$documentId',
    path: '/$documentId',
    getParentRoute: () => AuthenticatedClientsClientIdFireSafetyDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdJobPositionsIndexRoute =
  AuthenticatedClientsClientIdJobPositionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdJobPositionsRoute,
  } as any);
const AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute =
  AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteImport.update({
    id: '/$jobPositionId',
    path: '/$jobPositionId',
    getParentRoute: () => AuthenticatedClientsClientIdJobPositionsRoute,
  } as any);
const AuthenticatedClientsClientIdOtherDocumentsIndexRoute =
  AuthenticatedClientsClientIdOtherDocumentsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdOtherDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdOtherDocumentsContractRoute =
  AuthenticatedClientsClientIdOtherDocumentsContractRouteImport.update({
    id: '/contract',
    path: '/contract',
    getParentRoute: () => AuthenticatedClientsClientIdOtherDocumentsRoute,
  } as any);
const AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute =
  AuthenticatedClientsClientIdEmployeesEmployeeIdEditRouteImport.update({
    id: '/$employeeId_/edit',
    path: '/$employeeId/edit',
    getParentRoute: () => AuthenticatedClientsClientIdEmployeesRoute,
  } as any);
const AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute =
  AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute,
  } as any);
const AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute =
  AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRouteImport.update(
    {
      id: '/risk-evaluation',
      path: '/risk-evaluation',
      getParentRoute: () =>
        AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute,
    } as any,
  );
const AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute =
  AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRouteImport.update(
    {
      id: '/risk-evaluations/$evaluationId',
      path: '/risk-evaluations/$evaluationId',
      getParentRoute: () => AuthenticatedClientsClientIdJobPositionsRoute,
    } as any,
  );

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/accept-invitation': typeof AcceptInvitationRoute;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/contract': typeof ContractRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/clients': typeof AuthenticatedClientsRouteWithChildren;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/instructions': typeof AuthenticatedInstructionsRouteWithChildren;
  '/leads': typeof AuthenticatedLeadsRouteWithChildren;
  '/organization': typeof AuthenticatedOrganizationRouteWithChildren;
  '/profile': typeof AuthenticatedProfileRoute;
  '/risks': typeof AuthenticatedRisksRouteWithChildren;
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren;
  '/clients/new': typeof AuthenticatedClientsNewRoute;
  '/instructions/$moduleId': typeof AuthenticatedInstructionsModuleIdRoute;
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdRouteWithChildren;
  '/leads/new': typeof AuthenticatedLeadsNewRoute;
  '/organization/authorizations': typeof AuthenticatedOrganizationAuthorizationsRoute;
  '/organization/company': typeof AuthenticatedOrganizationCompanyRoute;
  '/organization/team': typeof AuthenticatedOrganizationTeamRoute;
  '/risks/$profileId': typeof AuthenticatedRisksProfileIdRoute;
  '/clients/': typeof AuthenticatedClientsIndexRoute;
  '/instructions/': typeof AuthenticatedInstructionsIndexRoute;
  '/leads/': typeof AuthenticatedLeadsIndexRoute;
  '/organization/': typeof AuthenticatedOrganizationIndexRoute;
  '/risks/': typeof AuthenticatedRisksIndexRoute;
  '/clients/$clientId/contact': typeof AuthenticatedClientsClientIdContactRoute;
  '/clients/$clientId/contract': typeof AuthenticatedClientsClientIdContractRouteWithChildren;
  '/clients/$clientId/details': typeof AuthenticatedClientsClientIdDetailsRoute;
  '/clients/$clientId/document-data': typeof AuthenticatedClientsClientIdDocumentDataRoute;
  '/clients/$clientId/documents': typeof AuthenticatedClientsClientIdDocumentsRouteWithChildren;
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute;
  '/clients/$clientId/employees': typeof AuthenticatedClientsClientIdEmployeesRouteWithChildren;
  '/clients/$clientId/fire-safety-documents': typeof AuthenticatedClientsClientIdFireSafetyDocumentsRouteWithChildren;
  '/clients/$clientId/job-positions': typeof AuthenticatedClientsClientIdJobPositionsRouteWithChildren;
  '/clients/$clientId/other-documents': typeof AuthenticatedClientsClientIdOtherDocumentsRouteWithChildren;
  '/clients/$clientId/training': typeof AuthenticatedClientsClientIdTrainingRoute;
  '/leads/$leadId/contract': typeof AuthenticatedLeadsLeadIdContractRoute;
  '/leads/$leadId/edit': typeof AuthenticatedLeadsLeadIdEditRoute;
  '/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute;
  '/leads/$leadId/': typeof AuthenticatedLeadsLeadIdIndexRoute;
  '/clients/$clientId/contract/edit': typeof AuthenticatedClientsClientIdContractEditRoute;
  '/clients/$clientId/documents/$documentId': typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  '/clients/$clientId/employees/$employeeId': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  '/clients/$clientId/employees/new': typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  '/clients/$clientId/fire-safety-documents/$documentId': typeof AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute;
  '/clients/$clientId/job-positions/$jobPositionId': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteWithChildren;
  '/clients/$clientId/other-documents/contract': typeof AuthenticatedClientsClientIdOtherDocumentsContractRoute;
  '/clients/$clientId/contract/': typeof AuthenticatedClientsClientIdContractIndexRoute;
  '/clients/$clientId/documents/': typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
  '/clients/$clientId/employees/': typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
  '/clients/$clientId/fire-safety-documents/': typeof AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute;
  '/clients/$clientId/job-positions/': typeof AuthenticatedClientsClientIdJobPositionsIndexRoute;
  '/clients/$clientId/other-documents/': typeof AuthenticatedClientsClientIdOtherDocumentsIndexRoute;
  '/clients/$clientId/employees/$employeeId/edit': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute;
  '/clients/$clientId/job-positions/$jobPositionId/risk-evaluation': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute;
  '/clients/$clientId/job-positions/risk-evaluations/$evaluationId': typeof AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute;
  '/clients/$clientId/job-positions/$jobPositionId/': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/accept-invitation': typeof AcceptInvitationRoute;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/contract': typeof ContractRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/dashboard': typeof AuthenticatedDashboardRoute;
  '/profile': typeof AuthenticatedProfileRoute;
  '/clients/new': typeof AuthenticatedClientsNewRoute;
  '/instructions/$moduleId': typeof AuthenticatedInstructionsModuleIdRoute;
  '/leads/new': typeof AuthenticatedLeadsNewRoute;
  '/organization/authorizations': typeof AuthenticatedOrganizationAuthorizationsRoute;
  '/organization/company': typeof AuthenticatedOrganizationCompanyRoute;
  '/organization/team': typeof AuthenticatedOrganizationTeamRoute;
  '/risks/$profileId': typeof AuthenticatedRisksProfileIdRoute;
  '/clients': typeof AuthenticatedClientsIndexRoute;
  '/instructions': typeof AuthenticatedInstructionsIndexRoute;
  '/leads': typeof AuthenticatedLeadsIndexRoute;
  '/organization': typeof AuthenticatedOrganizationIndexRoute;
  '/risks': typeof AuthenticatedRisksIndexRoute;
  '/clients/$clientId/contact': typeof AuthenticatedClientsClientIdContactRoute;
  '/clients/$clientId/details': typeof AuthenticatedClientsClientIdDetailsRoute;
  '/clients/$clientId/document-data': typeof AuthenticatedClientsClientIdDocumentDataRoute;
  '/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute;
  '/clients/$clientId/training': typeof AuthenticatedClientsClientIdTrainingRoute;
  '/leads/$leadId/contract': typeof AuthenticatedLeadsLeadIdContractRoute;
  '/leads/$leadId/edit': typeof AuthenticatedLeadsLeadIdEditRoute;
  '/clients/$clientId': typeof AuthenticatedClientsClientIdIndexRoute;
  '/leads/$leadId': typeof AuthenticatedLeadsLeadIdIndexRoute;
  '/clients/$clientId/contract/edit': typeof AuthenticatedClientsClientIdContractEditRoute;
  '/clients/$clientId/documents/$documentId': typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  '/clients/$clientId/employees/$employeeId': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  '/clients/$clientId/employees/new': typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  '/clients/$clientId/fire-safety-documents/$documentId': typeof AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute;
  '/clients/$clientId/other-documents/contract': typeof AuthenticatedClientsClientIdOtherDocumentsContractRoute;
  '/clients/$clientId/contract': typeof AuthenticatedClientsClientIdContractIndexRoute;
  '/clients/$clientId/documents': typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
  '/clients/$clientId/employees': typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
  '/clients/$clientId/fire-safety-documents': typeof AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute;
  '/clients/$clientId/job-positions': typeof AuthenticatedClientsClientIdJobPositionsIndexRoute;
  '/clients/$clientId/other-documents': typeof AuthenticatedClientsClientIdOtherDocumentsIndexRoute;
  '/clients/$clientId/employees/$employeeId/edit': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute;
  '/clients/$clientId/job-positions/$jobPositionId/risk-evaluation': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute;
  '/clients/$clientId/job-positions/risk-evaluations/$evaluationId': typeof AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute;
  '/clients/$clientId/job-positions/$jobPositionId': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/accept-invitation': typeof AcceptInvitationRoute;
  '/confirm-email': typeof ConfirmEmailRoute;
  '/contract': typeof ContractRoute;
  '/forgot-password': typeof ForgotPasswordRoute;
  '/login': typeof LoginRoute;
  '/onboarding': typeof OnboardingRoute;
  '/register': typeof RegisterRoute;
  '/reset-password': typeof ResetPasswordRoute;
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren;
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute;
  '/_authenticated/instructions': typeof AuthenticatedInstructionsRouteWithChildren;
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren;
  '/_authenticated/organization': typeof AuthenticatedOrganizationRouteWithChildren;
  '/_authenticated/profile': typeof AuthenticatedProfileRoute;
  '/_authenticated/risks': typeof AuthenticatedRisksRouteWithChildren;
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren;
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute;
  '/_authenticated/instructions/$moduleId': typeof AuthenticatedInstructionsModuleIdRoute;
  '/_authenticated/leads/$leadId': typeof AuthenticatedLeadsLeadIdRouteWithChildren;
  '/_authenticated/leads/new': typeof AuthenticatedLeadsNewRoute;
  '/_authenticated/organization/authorizations': typeof AuthenticatedOrganizationAuthorizationsRoute;
  '/_authenticated/organization/company': typeof AuthenticatedOrganizationCompanyRoute;
  '/_authenticated/organization/team': typeof AuthenticatedOrganizationTeamRoute;
  '/_authenticated/risks/$profileId': typeof AuthenticatedRisksProfileIdRoute;
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute;
  '/_authenticated/instructions/': typeof AuthenticatedInstructionsIndexRoute;
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute;
  '/_authenticated/organization/': typeof AuthenticatedOrganizationIndexRoute;
  '/_authenticated/risks/': typeof AuthenticatedRisksIndexRoute;
  '/_authenticated/clients/$clientId/contact': typeof AuthenticatedClientsClientIdContactRoute;
  '/_authenticated/clients/$clientId/contract': typeof AuthenticatedClientsClientIdContractRouteWithChildren;
  '/_authenticated/clients/$clientId/details': typeof AuthenticatedClientsClientIdDetailsRoute;
  '/_authenticated/clients/$clientId/document-data': typeof AuthenticatedClientsClientIdDocumentDataRoute;
  '/_authenticated/clients/$clientId/documents': typeof AuthenticatedClientsClientIdDocumentsRouteWithChildren;
  '/_authenticated/clients/$clientId/edit': typeof AuthenticatedClientsClientIdEditRoute;
  '/_authenticated/clients/$clientId/employees': typeof AuthenticatedClientsClientIdEmployeesRouteWithChildren;
  '/_authenticated/clients/$clientId/fire-safety-documents': typeof AuthenticatedClientsClientIdFireSafetyDocumentsRouteWithChildren;
  '/_authenticated/clients/$clientId/job-positions': typeof AuthenticatedClientsClientIdJobPositionsRouteWithChildren;
  '/_authenticated/clients/$clientId/other-documents': typeof AuthenticatedClientsClientIdOtherDocumentsRouteWithChildren;
  '/_authenticated/clients/$clientId/training': typeof AuthenticatedClientsClientIdTrainingRoute;
  '/_authenticated/leads/$leadId/contract': typeof AuthenticatedLeadsLeadIdContractRoute;
  '/_authenticated/leads/$leadId/edit': typeof AuthenticatedLeadsLeadIdEditRoute;
  '/_authenticated/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute;
  '/_authenticated/leads/$leadId/': typeof AuthenticatedLeadsLeadIdIndexRoute;
  '/_authenticated/clients/$clientId/contract/edit': typeof AuthenticatedClientsClientIdContractEditRoute;
  '/_authenticated/clients/$clientId/documents/$documentId': typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  '/_authenticated/clients/$clientId/employees/$employeeId': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  '/_authenticated/clients/$clientId/employees/new': typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  '/_authenticated/clients/$clientId/fire-safety-documents/$documentId': typeof AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute;
  '/_authenticated/clients/$clientId/job-positions/$jobPositionId': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteWithChildren;
  '/_authenticated/clients/$clientId/other-documents/contract': typeof AuthenticatedClientsClientIdOtherDocumentsContractRoute;
  '/_authenticated/clients/$clientId/contract/': typeof AuthenticatedClientsClientIdContractIndexRoute;
  '/_authenticated/clients/$clientId/documents/': typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
  '/_authenticated/clients/$clientId/employees/': typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
  '/_authenticated/clients/$clientId/fire-safety-documents/': typeof AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute;
  '/_authenticated/clients/$clientId/job-positions/': typeof AuthenticatedClientsClientIdJobPositionsIndexRoute;
  '/_authenticated/clients/$clientId/other-documents/': typeof AuthenticatedClientsClientIdOtherDocumentsIndexRoute;
  '/_authenticated/clients/$clientId/employees/$employeeId_/edit': typeof AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute;
  '/_authenticated/clients/$clientId/job-positions/$jobPositionId/risk-evaluation': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute;
  '/_authenticated/clients/$clientId/job-positions/risk-evaluations/$evaluationId': typeof AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute;
  '/_authenticated/clients/$clientId/job-positions/$jobPositionId/': typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/confirm-email'
    | '/contract'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/clients'
    | '/dashboard'
    | '/instructions'
    | '/leads'
    | '/organization'
    | '/profile'
    | '/risks'
    | '/clients/$clientId'
    | '/clients/new'
    | '/instructions/$moduleId'
    | '/leads/$leadId'
    | '/leads/new'
    | '/organization/authorizations'
    | '/organization/company'
    | '/organization/team'
    | '/risks/$profileId'
    | '/clients/'
    | '/instructions/'
    | '/leads/'
    | '/organization/'
    | '/risks/'
    | '/clients/$clientId/contact'
    | '/clients/$clientId/contract'
    | '/clients/$clientId/details'
    | '/clients/$clientId/document-data'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/edit'
    | '/clients/$clientId/employees'
    | '/clients/$clientId/fire-safety-documents'
    | '/clients/$clientId/job-positions'
    | '/clients/$clientId/other-documents'
    | '/clients/$clientId/training'
    | '/leads/$leadId/contract'
    | '/leads/$leadId/edit'
    | '/clients/$clientId/'
    | '/leads/$leadId/'
    | '/clients/$clientId/contract/edit'
    | '/clients/$clientId/documents/$documentId'
    | '/clients/$clientId/employees/$employeeId'
    | '/clients/$clientId/employees/new'
    | '/clients/$clientId/fire-safety-documents/$documentId'
    | '/clients/$clientId/job-positions/$jobPositionId'
    | '/clients/$clientId/other-documents/contract'
    | '/clients/$clientId/contract/'
    | '/clients/$clientId/documents/'
    | '/clients/$clientId/employees/'
    | '/clients/$clientId/fire-safety-documents/'
    | '/clients/$clientId/job-positions/'
    | '/clients/$clientId/other-documents/'
    | '/clients/$clientId/employees/$employeeId/edit'
    | '/clients/$clientId/job-positions/$jobPositionId/risk-evaluation'
    | '/clients/$clientId/job-positions/risk-evaluations/$evaluationId'
    | '/clients/$clientId/job-positions/$jobPositionId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/accept-invitation'
    | '/confirm-email'
    | '/contract'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/profile'
    | '/clients/new'
    | '/instructions/$moduleId'
    | '/leads/new'
    | '/organization/authorizations'
    | '/organization/company'
    | '/organization/team'
    | '/risks/$profileId'
    | '/clients'
    | '/instructions'
    | '/leads'
    | '/organization'
    | '/risks'
    | '/clients/$clientId/contact'
    | '/clients/$clientId/details'
    | '/clients/$clientId/document-data'
    | '/clients/$clientId/edit'
    | '/clients/$clientId/training'
    | '/leads/$leadId/contract'
    | '/leads/$leadId/edit'
    | '/clients/$clientId'
    | '/leads/$leadId'
    | '/clients/$clientId/contract/edit'
    | '/clients/$clientId/documents/$documentId'
    | '/clients/$clientId/employees/$employeeId'
    | '/clients/$clientId/employees/new'
    | '/clients/$clientId/fire-safety-documents/$documentId'
    | '/clients/$clientId/other-documents/contract'
    | '/clients/$clientId/contract'
    | '/clients/$clientId/documents'
    | '/clients/$clientId/employees'
    | '/clients/$clientId/fire-safety-documents'
    | '/clients/$clientId/job-positions'
    | '/clients/$clientId/other-documents'
    | '/clients/$clientId/employees/$employeeId/edit'
    | '/clients/$clientId/job-positions/$jobPositionId/risk-evaluation'
    | '/clients/$clientId/job-positions/risk-evaluations/$evaluationId'
    | '/clients/$clientId/job-positions/$jobPositionId';
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/confirm-email'
    | '/contract'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/reset-password'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/instructions'
    | '/_authenticated/leads'
    | '/_authenticated/organization'
    | '/_authenticated/profile'
    | '/_authenticated/risks'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/clients/new'
    | '/_authenticated/instructions/$moduleId'
    | '/_authenticated/leads/$leadId'
    | '/_authenticated/leads/new'
    | '/_authenticated/organization/authorizations'
    | '/_authenticated/organization/company'
    | '/_authenticated/organization/team'
    | '/_authenticated/risks/$profileId'
    | '/_authenticated/clients/'
    | '/_authenticated/instructions/'
    | '/_authenticated/leads/'
    | '/_authenticated/organization/'
    | '/_authenticated/risks/'
    | '/_authenticated/clients/$clientId/contact'
    | '/_authenticated/clients/$clientId/contract'
    | '/_authenticated/clients/$clientId/details'
    | '/_authenticated/clients/$clientId/document-data'
    | '/_authenticated/clients/$clientId/documents'
    | '/_authenticated/clients/$clientId/edit'
    | '/_authenticated/clients/$clientId/employees'
    | '/_authenticated/clients/$clientId/fire-safety-documents'
    | '/_authenticated/clients/$clientId/job-positions'
    | '/_authenticated/clients/$clientId/other-documents'
    | '/_authenticated/clients/$clientId/training'
    | '/_authenticated/leads/$leadId/contract'
    | '/_authenticated/leads/$leadId/edit'
    | '/_authenticated/clients/$clientId/'
    | '/_authenticated/leads/$leadId/'
    | '/_authenticated/clients/$clientId/contract/edit'
    | '/_authenticated/clients/$clientId/documents/$documentId'
    | '/_authenticated/clients/$clientId/employees/$employeeId'
    | '/_authenticated/clients/$clientId/employees/new'
    | '/_authenticated/clients/$clientId/fire-safety-documents/$documentId'
    | '/_authenticated/clients/$clientId/job-positions/$jobPositionId'
    | '/_authenticated/clients/$clientId/other-documents/contract'
    | '/_authenticated/clients/$clientId/contract/'
    | '/_authenticated/clients/$clientId/documents/'
    | '/_authenticated/clients/$clientId/employees/'
    | '/_authenticated/clients/$clientId/fire-safety-documents/'
    | '/_authenticated/clients/$clientId/job-positions/'
    | '/_authenticated/clients/$clientId/other-documents/'
    | '/_authenticated/clients/$clientId/employees/$employeeId_/edit'
    | '/_authenticated/clients/$clientId/job-positions/$jobPositionId/risk-evaluation'
    | '/_authenticated/clients/$clientId/job-positions/risk-evaluations/$evaluationId'
    | '/_authenticated/clients/$clientId/job-positions/$jobPositionId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  AcceptInvitationRoute: typeof AcceptInvitationRoute;
  ConfirmEmailRoute: typeof ConfirmEmailRoute;
  ContractRoute: typeof ContractRoute;
  ForgotPasswordRoute: typeof ForgotPasswordRoute;
  LoginRoute: typeof LoginRoute;
  OnboardingRoute: typeof OnboardingRoute;
  RegisterRoute: typeof RegisterRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/accept-invitation': {
      id: '/accept-invitation';
      path: '/accept-invitation';
      fullPath: '/accept-invitation';
      preLoaderRoute: typeof AcceptInvitationRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/confirm-email': {
      id: '/confirm-email';
      path: '/confirm-email';
      fullPath: '/confirm-email';
      preLoaderRoute: typeof ConfirmEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/contract': {
      id: '/contract';
      path: '/contract';
      fullPath: '/contract';
      preLoaderRoute: typeof ContractRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/forgot-password': {
      id: '/forgot-password';
      path: '/forgot-password';
      fullPath: '/forgot-password';
      preLoaderRoute: typeof ForgotPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/onboarding': {
      id: '/onboarding';
      path: '/onboarding';
      fullPath: '/onboarding';
      preLoaderRoute: typeof OnboardingRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/register': {
      id: '/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/reset-password': {
      id: '/reset-password';
      path: '/reset-password';
      fullPath: '/reset-password';
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/clients': {
      id: '/_authenticated/clients';
      path: '/clients';
      fullPath: '/clients';
      preLoaderRoute: typeof AuthenticatedClientsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/instructions': {
      id: '/_authenticated/instructions';
      path: '/instructions';
      fullPath: '/instructions';
      preLoaderRoute: typeof AuthenticatedInstructionsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/leads': {
      id: '/_authenticated/leads';
      path: '/leads';
      fullPath: '/leads';
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/organization': {
      id: '/_authenticated/organization';
      path: '/organization';
      fullPath: '/organization';
      preLoaderRoute: typeof AuthenticatedOrganizationRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/profile': {
      id: '/_authenticated/profile';
      path: '/profile';
      fullPath: '/profile';
      preLoaderRoute: typeof AuthenticatedProfileRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/risks': {
      id: '/_authenticated/risks';
      path: '/risks';
      fullPath: '/risks';
      preLoaderRoute: typeof AuthenticatedRisksRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/';
      path: '/';
      fullPath: '/clients/';
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsRoute;
    };
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId';
      path: '/$clientId';
      fullPath: '/clients/$clientId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport;
      parentRoute: typeof AuthenticatedClientsRoute;
    };
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new';
      path: '/new';
      fullPath: '/clients/new';
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport;
      parentRoute: typeof AuthenticatedClientsRoute;
    };
    '/_authenticated/instructions/': {
      id: '/_authenticated/instructions/';
      path: '/';
      fullPath: '/instructions/';
      preLoaderRoute: typeof AuthenticatedInstructionsIndexRouteImport;
      parentRoute: typeof AuthenticatedInstructionsRoute;
    };
    '/_authenticated/instructions/$moduleId': {
      id: '/_authenticated/instructions/$moduleId';
      path: '/$moduleId';
      fullPath: '/instructions/$moduleId';
      preLoaderRoute: typeof AuthenticatedInstructionsModuleIdRouteImport;
      parentRoute: typeof AuthenticatedInstructionsRoute;
    };
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/';
      path: '/';
      fullPath: '/leads/';
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport;
      parentRoute: typeof AuthenticatedLeadsRoute;
    };
    '/_authenticated/leads/$leadId': {
      id: '/_authenticated/leads/$leadId';
      path: '/$leadId';
      fullPath: '/leads/$leadId';
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdRouteImport;
      parentRoute: typeof AuthenticatedLeadsRoute;
    };
    '/_authenticated/leads/new': {
      id: '/_authenticated/leads/new';
      path: '/new';
      fullPath: '/leads/new';
      preLoaderRoute: typeof AuthenticatedLeadsNewRouteImport;
      parentRoute: typeof AuthenticatedLeadsRoute;
    };
    '/_authenticated/organization/': {
      id: '/_authenticated/organization/';
      path: '/';
      fullPath: '/organization/';
      preLoaderRoute: typeof AuthenticatedOrganizationIndexRouteImport;
      parentRoute: typeof AuthenticatedOrganizationRoute;
    };
    '/_authenticated/organization/authorizations': {
      id: '/_authenticated/organization/authorizations';
      path: '/authorizations';
      fullPath: '/organization/authorizations';
      preLoaderRoute: typeof AuthenticatedOrganizationAuthorizationsRouteImport;
      parentRoute: typeof AuthenticatedOrganizationRoute;
    };
    '/_authenticated/organization/company': {
      id: '/_authenticated/organization/company';
      path: '/company';
      fullPath: '/organization/company';
      preLoaderRoute: typeof AuthenticatedOrganizationCompanyRouteImport;
      parentRoute: typeof AuthenticatedOrganizationRoute;
    };
    '/_authenticated/organization/team': {
      id: '/_authenticated/organization/team';
      path: '/team';
      fullPath: '/organization/team';
      preLoaderRoute: typeof AuthenticatedOrganizationTeamRouteImport;
      parentRoute: typeof AuthenticatedOrganizationRoute;
    };
    '/_authenticated/risks/': {
      id: '/_authenticated/risks/';
      path: '/';
      fullPath: '/risks/';
      preLoaderRoute: typeof AuthenticatedRisksIndexRouteImport;
      parentRoute: typeof AuthenticatedRisksRoute;
    };
    '/_authenticated/risks/$profileId': {
      id: '/_authenticated/risks/$profileId';
      path: '/$profileId';
      fullPath: '/risks/$profileId';
      preLoaderRoute: typeof AuthenticatedRisksProfileIdRouteImport;
      parentRoute: typeof AuthenticatedRisksRoute;
    };
    '/_authenticated/clients/$clientId/': {
      id: '/_authenticated/clients/$clientId/';
      path: '/';
      fullPath: '/clients/$clientId/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/contact': {
      id: '/_authenticated/clients/$clientId/contact';
      path: '/contact';
      fullPath: '/clients/$clientId/contact';
      preLoaderRoute: typeof AuthenticatedClientsClientIdContactRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/contract': {
      id: '/_authenticated/clients/$clientId/contract';
      path: '/contract';
      fullPath: '/clients/$clientId/contract';
      preLoaderRoute: typeof AuthenticatedClientsClientIdContractRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/details': {
      id: '/_authenticated/clients/$clientId/details';
      path: '/details';
      fullPath: '/clients/$clientId/details';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDetailsRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/document-data': {
      id: '/_authenticated/clients/$clientId/document-data';
      path: '/document-data';
      fullPath: '/clients/$clientId/document-data';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentDataRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/documents': {
      id: '/_authenticated/clients/$clientId/documents';
      path: '/documents';
      fullPath: '/clients/$clientId/documents';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentsRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/edit': {
      id: '/_authenticated/clients/$clientId/edit';
      path: '/edit';
      fullPath: '/clients/$clientId/edit';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEditRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/employees': {
      id: '/_authenticated/clients/$clientId/employees';
      path: '/employees';
      fullPath: '/clients/$clientId/employees';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/fire-safety-documents': {
      id: '/_authenticated/clients/$clientId/fire-safety-documents';
      path: '/fire-safety-documents';
      fullPath: '/clients/$clientId/fire-safety-documents';
      preLoaderRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/job-positions': {
      id: '/_authenticated/clients/$clientId/job-positions';
      path: '/job-positions';
      fullPath: '/clients/$clientId/job-positions';
      preLoaderRoute: typeof AuthenticatedClientsClientIdJobPositionsRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/other-documents': {
      id: '/_authenticated/clients/$clientId/other-documents';
      path: '/other-documents';
      fullPath: '/clients/$clientId/other-documents';
      preLoaderRoute: typeof AuthenticatedClientsClientIdOtherDocumentsRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/clients/$clientId/training': {
      id: '/_authenticated/clients/$clientId/training';
      path: '/training';
      fullPath: '/clients/$clientId/training';
      preLoaderRoute: typeof AuthenticatedClientsClientIdTrainingRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdRoute;
    };
    '/_authenticated/leads/$leadId/': {
      id: '/_authenticated/leads/$leadId/';
      path: '/';
      fullPath: '/leads/$leadId/';
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdIndexRouteImport;
      parentRoute: typeof AuthenticatedLeadsLeadIdRoute;
    };
    '/_authenticated/leads/$leadId/contract': {
      id: '/_authenticated/leads/$leadId/contract';
      path: '/contract';
      fullPath: '/leads/$leadId/contract';
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdContractRouteImport;
      parentRoute: typeof AuthenticatedLeadsLeadIdRoute;
    };
    '/_authenticated/leads/$leadId/edit': {
      id: '/_authenticated/leads/$leadId/edit';
      path: '/edit';
      fullPath: '/leads/$leadId/edit';
      preLoaderRoute: typeof AuthenticatedLeadsLeadIdEditRouteImport;
      parentRoute: typeof AuthenticatedLeadsLeadIdRoute;
    };
    '/_authenticated/clients/$clientId/contract/': {
      id: '/_authenticated/clients/$clientId/contract/';
      path: '/';
      fullPath: '/clients/$clientId/contract/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdContractIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdContractRoute;
    };
    '/_authenticated/clients/$clientId/contract/edit': {
      id: '/_authenticated/clients/$clientId/contract/edit';
      path: '/edit';
      fullPath: '/clients/$clientId/contract/edit';
      preLoaderRoute: typeof AuthenticatedClientsClientIdContractEditRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdContractRoute;
    };
    '/_authenticated/clients/$clientId/documents/': {
      id: '/_authenticated/clients/$clientId/documents/';
      path: '/';
      fullPath: '/clients/$clientId/documents/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentsIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/documents/$documentId': {
      id: '/_authenticated/clients/$clientId/documents/$documentId';
      path: '/$documentId';
      fullPath: '/clients/$clientId/documents/$documentId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdDocumentsDocumentIdRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/employees/': {
      id: '/_authenticated/clients/$clientId/employees/';
      path: '/';
      fullPath: '/clients/$clientId/employees/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdEmployeesRoute;
    };
    '/_authenticated/clients/$clientId/employees/$employeeId': {
      id: '/_authenticated/clients/$clientId/employees/$employeeId';
      path: '/$employeeId';
      fullPath: '/clients/$clientId/employees/$employeeId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdEmployeesRoute;
    };
    '/_authenticated/clients/$clientId/employees/new': {
      id: '/_authenticated/clients/$clientId/employees/new';
      path: '/new';
      fullPath: '/clients/$clientId/employees/new';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesNewRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdEmployeesRoute;
    };
    '/_authenticated/clients/$clientId/fire-safety-documents/': {
      id: '/_authenticated/clients/$clientId/fire-safety-documents/';
      path: '/';
      fullPath: '/clients/$clientId/fire-safety-documents/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/fire-safety-documents/$documentId': {
      id: '/_authenticated/clients/$clientId/fire-safety-documents/$documentId';
      path: '/$documentId';
      fullPath: '/clients/$clientId/fire-safety-documents/$documentId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/job-positions/': {
      id: '/_authenticated/clients/$clientId/job-positions/';
      path: '/';
      fullPath: '/clients/$clientId/job-positions/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdJobPositionsIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdJobPositionsRoute;
    };
    '/_authenticated/clients/$clientId/job-positions/$jobPositionId': {
      id: '/_authenticated/clients/$clientId/job-positions/$jobPositionId';
      path: '/$jobPositionId';
      fullPath: '/clients/$clientId/job-positions/$jobPositionId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdJobPositionsRoute;
    };
    '/_authenticated/clients/$clientId/other-documents/': {
      id: '/_authenticated/clients/$clientId/other-documents/';
      path: '/';
      fullPath: '/clients/$clientId/other-documents/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdOtherDocumentsIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdOtherDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/other-documents/contract': {
      id: '/_authenticated/clients/$clientId/other-documents/contract';
      path: '/contract';
      fullPath: '/clients/$clientId/other-documents/contract';
      preLoaderRoute: typeof AuthenticatedClientsClientIdOtherDocumentsContractRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdOtherDocumentsRoute;
    };
    '/_authenticated/clients/$clientId/employees/$employeeId_/edit': {
      id: '/_authenticated/clients/$clientId/employees/$employeeId_/edit';
      path: '/$employeeId/edit';
      fullPath: '/clients/$clientId/employees/$employeeId/edit';
      preLoaderRoute: typeof AuthenticatedClientsClientIdEmployeesEmployeeIdEditRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdEmployeesRoute;
    };
    '/_authenticated/clients/$clientId/job-positions/$jobPositionId/': {
      id: '/_authenticated/clients/$clientId/job-positions/$jobPositionId/';
      path: '/';
      fullPath: '/clients/$clientId/job-positions/$jobPositionId/';
      preLoaderRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute;
    };
    '/_authenticated/clients/$clientId/job-positions/$jobPositionId/risk-evaluation': {
      id: '/_authenticated/clients/$clientId/job-positions/$jobPositionId/risk-evaluation';
      path: '/risk-evaluation';
      fullPath: '/clients/$clientId/job-positions/$jobPositionId/risk-evaluation';
      preLoaderRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute;
    };
    '/_authenticated/clients/$clientId/job-positions/risk-evaluations/$evaluationId': {
      id: '/_authenticated/clients/$clientId/job-positions/risk-evaluations/$evaluationId';
      path: '/risk-evaluations/$evaluationId';
      fullPath: '/clients/$clientId/job-positions/risk-evaluations/$evaluationId';
      preLoaderRoute: typeof AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRouteImport;
      parentRoute: typeof AuthenticatedClientsClientIdJobPositionsRoute;
    };
  }
}

interface AuthenticatedClientsClientIdContractRouteChildren {
  AuthenticatedClientsClientIdContractEditRoute: typeof AuthenticatedClientsClientIdContractEditRoute;
  AuthenticatedClientsClientIdContractIndexRoute: typeof AuthenticatedClientsClientIdContractIndexRoute;
}

const AuthenticatedClientsClientIdContractRouteChildren: AuthenticatedClientsClientIdContractRouteChildren =
  {
    AuthenticatedClientsClientIdContractEditRoute:
      AuthenticatedClientsClientIdContractEditRoute,
    AuthenticatedClientsClientIdContractIndexRoute:
      AuthenticatedClientsClientIdContractIndexRoute,
  };

const AuthenticatedClientsClientIdContractRouteWithChildren =
  AuthenticatedClientsClientIdContractRoute._addFileChildren(
    AuthenticatedClientsClientIdContractRouteChildren,
  );

interface AuthenticatedClientsClientIdDocumentsRouteChildren {
  AuthenticatedClientsClientIdDocumentsDocumentIdRoute: typeof AuthenticatedClientsClientIdDocumentsDocumentIdRoute;
  AuthenticatedClientsClientIdDocumentsIndexRoute: typeof AuthenticatedClientsClientIdDocumentsIndexRoute;
}

const AuthenticatedClientsClientIdDocumentsRouteChildren: AuthenticatedClientsClientIdDocumentsRouteChildren =
  {
    AuthenticatedClientsClientIdDocumentsDocumentIdRoute:
      AuthenticatedClientsClientIdDocumentsDocumentIdRoute,
    AuthenticatedClientsClientIdDocumentsIndexRoute:
      AuthenticatedClientsClientIdDocumentsIndexRoute,
  };

const AuthenticatedClientsClientIdDocumentsRouteWithChildren =
  AuthenticatedClientsClientIdDocumentsRoute._addFileChildren(
    AuthenticatedClientsClientIdDocumentsRouteChildren,
  );

interface AuthenticatedClientsClientIdEmployeesRouteChildren {
  AuthenticatedClientsClientIdEmployeesEmployeeIdRoute: typeof AuthenticatedClientsClientIdEmployeesEmployeeIdRoute;
  AuthenticatedClientsClientIdEmployeesNewRoute: typeof AuthenticatedClientsClientIdEmployeesNewRoute;
  AuthenticatedClientsClientIdEmployeesIndexRoute: typeof AuthenticatedClientsClientIdEmployeesIndexRoute;
  AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute: typeof AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute;
}

const AuthenticatedClientsClientIdEmployeesRouteChildren: AuthenticatedClientsClientIdEmployeesRouteChildren =
  {
    AuthenticatedClientsClientIdEmployeesEmployeeIdRoute:
      AuthenticatedClientsClientIdEmployeesEmployeeIdRoute,
    AuthenticatedClientsClientIdEmployeesNewRoute:
      AuthenticatedClientsClientIdEmployeesNewRoute,
    AuthenticatedClientsClientIdEmployeesIndexRoute:
      AuthenticatedClientsClientIdEmployeesIndexRoute,
    AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute:
      AuthenticatedClientsClientIdEmployeesEmployeeIdEditRoute,
  };

const AuthenticatedClientsClientIdEmployeesRouteWithChildren =
  AuthenticatedClientsClientIdEmployeesRoute._addFileChildren(
    AuthenticatedClientsClientIdEmployeesRouteChildren,
  );

interface AuthenticatedClientsClientIdFireSafetyDocumentsRouteChildren {
  AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute;
  AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute;
}

const AuthenticatedClientsClientIdFireSafetyDocumentsRouteChildren: AuthenticatedClientsClientIdFireSafetyDocumentsRouteChildren =
  {
    AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute:
      AuthenticatedClientsClientIdFireSafetyDocumentsDocumentIdRoute,
    AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute:
      AuthenticatedClientsClientIdFireSafetyDocumentsIndexRoute,
  };

const AuthenticatedClientsClientIdFireSafetyDocumentsRouteWithChildren =
  AuthenticatedClientsClientIdFireSafetyDocumentsRoute._addFileChildren(
    AuthenticatedClientsClientIdFireSafetyDocumentsRouteChildren,
  );

interface AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteChildren {
  AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute;
  AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute;
}

const AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteChildren: AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteChildren =
  {
    AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute:
      AuthenticatedClientsClientIdJobPositionsJobPositionIdRiskEvaluationRoute,
    AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute:
      AuthenticatedClientsClientIdJobPositionsJobPositionIdIndexRoute,
  };

const AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteWithChildren =
  AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute._addFileChildren(
    AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteChildren,
  );

interface AuthenticatedClientsClientIdJobPositionsRouteChildren {
  AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute: typeof AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteWithChildren;
  AuthenticatedClientsClientIdJobPositionsIndexRoute: typeof AuthenticatedClientsClientIdJobPositionsIndexRoute;
  AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute: typeof AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute;
}

const AuthenticatedClientsClientIdJobPositionsRouteChildren: AuthenticatedClientsClientIdJobPositionsRouteChildren =
  {
    AuthenticatedClientsClientIdJobPositionsJobPositionIdRoute:
      AuthenticatedClientsClientIdJobPositionsJobPositionIdRouteWithChildren,
    AuthenticatedClientsClientIdJobPositionsIndexRoute:
      AuthenticatedClientsClientIdJobPositionsIndexRoute,
    AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute:
      AuthenticatedClientsClientIdJobPositionsRiskEvaluationsEvaluationIdRoute,
  };

const AuthenticatedClientsClientIdJobPositionsRouteWithChildren =
  AuthenticatedClientsClientIdJobPositionsRoute._addFileChildren(
    AuthenticatedClientsClientIdJobPositionsRouteChildren,
  );

interface AuthenticatedClientsClientIdOtherDocumentsRouteChildren {
  AuthenticatedClientsClientIdOtherDocumentsContractRoute: typeof AuthenticatedClientsClientIdOtherDocumentsContractRoute;
  AuthenticatedClientsClientIdOtherDocumentsIndexRoute: typeof AuthenticatedClientsClientIdOtherDocumentsIndexRoute;
}

const AuthenticatedClientsClientIdOtherDocumentsRouteChildren: AuthenticatedClientsClientIdOtherDocumentsRouteChildren =
  {
    AuthenticatedClientsClientIdOtherDocumentsContractRoute:
      AuthenticatedClientsClientIdOtherDocumentsContractRoute,
    AuthenticatedClientsClientIdOtherDocumentsIndexRoute:
      AuthenticatedClientsClientIdOtherDocumentsIndexRoute,
  };

const AuthenticatedClientsClientIdOtherDocumentsRouteWithChildren =
  AuthenticatedClientsClientIdOtherDocumentsRoute._addFileChildren(
    AuthenticatedClientsClientIdOtherDocumentsRouteChildren,
  );

interface AuthenticatedClientsClientIdRouteChildren {
  AuthenticatedClientsClientIdContactRoute: typeof AuthenticatedClientsClientIdContactRoute;
  AuthenticatedClientsClientIdContractRoute: typeof AuthenticatedClientsClientIdContractRouteWithChildren;
  AuthenticatedClientsClientIdDetailsRoute: typeof AuthenticatedClientsClientIdDetailsRoute;
  AuthenticatedClientsClientIdDocumentDataRoute: typeof AuthenticatedClientsClientIdDocumentDataRoute;
  AuthenticatedClientsClientIdDocumentsRoute: typeof AuthenticatedClientsClientIdDocumentsRouteWithChildren;
  AuthenticatedClientsClientIdEditRoute: typeof AuthenticatedClientsClientIdEditRoute;
  AuthenticatedClientsClientIdEmployeesRoute: typeof AuthenticatedClientsClientIdEmployeesRouteWithChildren;
  AuthenticatedClientsClientIdFireSafetyDocumentsRoute: typeof AuthenticatedClientsClientIdFireSafetyDocumentsRouteWithChildren;
  AuthenticatedClientsClientIdJobPositionsRoute: typeof AuthenticatedClientsClientIdJobPositionsRouteWithChildren;
  AuthenticatedClientsClientIdOtherDocumentsRoute: typeof AuthenticatedClientsClientIdOtherDocumentsRouteWithChildren;
  AuthenticatedClientsClientIdTrainingRoute: typeof AuthenticatedClientsClientIdTrainingRoute;
  AuthenticatedClientsClientIdIndexRoute: typeof AuthenticatedClientsClientIdIndexRoute;
}

const AuthenticatedClientsClientIdRouteChildren: AuthenticatedClientsClientIdRouteChildren =
  {
    AuthenticatedClientsClientIdContactRoute:
      AuthenticatedClientsClientIdContactRoute,
    AuthenticatedClientsClientIdContractRoute:
      AuthenticatedClientsClientIdContractRouteWithChildren,
    AuthenticatedClientsClientIdDetailsRoute:
      AuthenticatedClientsClientIdDetailsRoute,
    AuthenticatedClientsClientIdDocumentDataRoute:
      AuthenticatedClientsClientIdDocumentDataRoute,
    AuthenticatedClientsClientIdDocumentsRoute:
      AuthenticatedClientsClientIdDocumentsRouteWithChildren,
    AuthenticatedClientsClientIdEditRoute:
      AuthenticatedClientsClientIdEditRoute,
    AuthenticatedClientsClientIdEmployeesRoute:
      AuthenticatedClientsClientIdEmployeesRouteWithChildren,
    AuthenticatedClientsClientIdFireSafetyDocumentsRoute:
      AuthenticatedClientsClientIdFireSafetyDocumentsRouteWithChildren,
    AuthenticatedClientsClientIdJobPositionsRoute:
      AuthenticatedClientsClientIdJobPositionsRouteWithChildren,
    AuthenticatedClientsClientIdOtherDocumentsRoute:
      AuthenticatedClientsClientIdOtherDocumentsRouteWithChildren,
    AuthenticatedClientsClientIdTrainingRoute:
      AuthenticatedClientsClientIdTrainingRoute,
    AuthenticatedClientsClientIdIndexRoute:
      AuthenticatedClientsClientIdIndexRoute,
  };

const AuthenticatedClientsClientIdRouteWithChildren =
  AuthenticatedClientsClientIdRoute._addFileChildren(
    AuthenticatedClientsClientIdRouteChildren,
  );

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRouteWithChildren;
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute;
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute;
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute:
    AuthenticatedClientsClientIdRouteWithChildren,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
};

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren);

interface AuthenticatedInstructionsRouteChildren {
  AuthenticatedInstructionsModuleIdRoute: typeof AuthenticatedInstructionsModuleIdRoute;
  AuthenticatedInstructionsIndexRoute: typeof AuthenticatedInstructionsIndexRoute;
}

const AuthenticatedInstructionsRouteChildren: AuthenticatedInstructionsRouteChildren =
  {
    AuthenticatedInstructionsModuleIdRoute:
      AuthenticatedInstructionsModuleIdRoute,
    AuthenticatedInstructionsIndexRoute: AuthenticatedInstructionsIndexRoute,
  };

const AuthenticatedInstructionsRouteWithChildren =
  AuthenticatedInstructionsRoute._addFileChildren(
    AuthenticatedInstructionsRouteChildren,
  );

interface AuthenticatedLeadsLeadIdRouteChildren {
  AuthenticatedLeadsLeadIdContractRoute: typeof AuthenticatedLeadsLeadIdContractRoute;
  AuthenticatedLeadsLeadIdEditRoute: typeof AuthenticatedLeadsLeadIdEditRoute;
  AuthenticatedLeadsLeadIdIndexRoute: typeof AuthenticatedLeadsLeadIdIndexRoute;
}

const AuthenticatedLeadsLeadIdRouteChildren: AuthenticatedLeadsLeadIdRouteChildren =
  {
    AuthenticatedLeadsLeadIdContractRoute:
      AuthenticatedLeadsLeadIdContractRoute,
    AuthenticatedLeadsLeadIdEditRoute: AuthenticatedLeadsLeadIdEditRoute,
    AuthenticatedLeadsLeadIdIndexRoute: AuthenticatedLeadsLeadIdIndexRoute,
  };

const AuthenticatedLeadsLeadIdRouteWithChildren =
  AuthenticatedLeadsLeadIdRoute._addFileChildren(
    AuthenticatedLeadsLeadIdRouteChildren,
  );

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsLeadIdRoute: typeof AuthenticatedLeadsLeadIdRouteWithChildren;
  AuthenticatedLeadsNewRoute: typeof AuthenticatedLeadsNewRoute;
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute;
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsLeadIdRoute: AuthenticatedLeadsLeadIdRouteWithChildren,
  AuthenticatedLeadsNewRoute: AuthenticatedLeadsNewRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
};

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren);

interface AuthenticatedOrganizationRouteChildren {
  AuthenticatedOrganizationAuthorizationsRoute: typeof AuthenticatedOrganizationAuthorizationsRoute;
  AuthenticatedOrganizationCompanyRoute: typeof AuthenticatedOrganizationCompanyRoute;
  AuthenticatedOrganizationTeamRoute: typeof AuthenticatedOrganizationTeamRoute;
  AuthenticatedOrganizationIndexRoute: typeof AuthenticatedOrganizationIndexRoute;
}

const AuthenticatedOrganizationRouteChildren: AuthenticatedOrganizationRouteChildren =
  {
    AuthenticatedOrganizationAuthorizationsRoute:
      AuthenticatedOrganizationAuthorizationsRoute,
    AuthenticatedOrganizationCompanyRoute:
      AuthenticatedOrganizationCompanyRoute,
    AuthenticatedOrganizationTeamRoute: AuthenticatedOrganizationTeamRoute,
    AuthenticatedOrganizationIndexRoute: AuthenticatedOrganizationIndexRoute,
  };

const AuthenticatedOrganizationRouteWithChildren =
  AuthenticatedOrganizationRoute._addFileChildren(
    AuthenticatedOrganizationRouteChildren,
  );

interface AuthenticatedRisksRouteChildren {
  AuthenticatedRisksProfileIdRoute: typeof AuthenticatedRisksProfileIdRoute;
  AuthenticatedRisksIndexRoute: typeof AuthenticatedRisksIndexRoute;
}

const AuthenticatedRisksRouteChildren: AuthenticatedRisksRouteChildren = {
  AuthenticatedRisksProfileIdRoute: AuthenticatedRisksProfileIdRoute,
  AuthenticatedRisksIndexRoute: AuthenticatedRisksIndexRoute,
};

const AuthenticatedRisksRouteWithChildren =
  AuthenticatedRisksRoute._addFileChildren(AuthenticatedRisksRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedInstructionsRoute: typeof AuthenticatedInstructionsRouteWithChildren;
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren;
  AuthenticatedOrganizationRoute: typeof AuthenticatedOrganizationRouteWithChildren;
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute;
  AuthenticatedRisksRoute: typeof AuthenticatedRisksRouteWithChildren;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInstructionsRoute: AuthenticatedInstructionsRouteWithChildren,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedOrganizationRoute: AuthenticatedOrganizationRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRisksRoute: AuthenticatedRisksRouteWithChildren,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ConfirmEmailRoute: ConfirmEmailRoute,
  ContractRoute: ContractRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
