import type { DocumentFacts } from './context';

export const workshopId = 'f1f1f1f1-0000-4000-8000-000000000001';
export const officeId = 'f1f1f1f1-0000-4000-8000-000000000002';
import {
  officeEvaluation,
  sensitiveGroupsEvaluation,
  workshopEvaluation,
} from './risk-evaluations.fixture';

export const facts: DocumentFacts = {
  issueDate: '2026-01-19',
  firstDecisionNumber: 5,
  branding: true,
  organization: {
    legalName: 'S.C. SERVICIU EXTERN DEMO S.R.L.',
    representativeName: 'Ana IONESCU',
    representativeRole: 'Administrator',
    fireSafetyTechnicianName: 'Radu STAN',
  },
  specialist: { fullName: 'Dan MARIN', professionalTitle: 'Evaluator de risc SSM' },
  client: {
    legalName: ' S.C. PIPETECH S.R.L. ',
    representativeName: 'Florin Cristian TALOȘ',
    representativeRole: 'Administrator',
    periodicTrainingMinutes: 120,
    administrativeTrainingIntervalMonths: 6,
    administrativeTrainingNotApplicable: false,
    workerTrainingIntervalMonths: 3,
    workerTrainingNotApplicable: false,
    trainingFirstMonth: 2,
    trainingDayFrom: 2,
    trainingDayTo: 7,
    caenCode: '2562',
  },
  workplaces: [
    {
      id: workshopId,
      name: 'Atelier Ghiroda',
      registeredOffice: false,
      countyCode: 'TM',
      locality: 'Ghiroda',
      addressLine: 'Str. Industriilor 4',
      activity: 'Atelier de sudură ',
      floorAreaM2: 420,
      extinguisherNorm: 'other_150',
      assemblyPoint: 'Parcarea din fața atelierului',
      combustibleMaterials: 'Lemn, cartoane, uleiuri de motor',
      ignitionSources: 'Arcul electric, scântei de la polizare',
      fireRiskEquipment: 'Aparate de sudură, polizoare unghiulare',
      specificMeasures: 'Sudura numai cu permis de lucru cu foc.',
    },
    {
      id: officeId,
      name: 'Sediul social',
      registeredOffice: true,
      countyCode: 'B',
      locality: 'Sector 1',
      addressLine: 'Calea Victoriei 122A',
      activity: 'Birouri',
      floorAreaM2: 180,
      extinguisherNorm: 'administrative_300',
      assemblyPoint: 'Curtea interioară',
      combustibleMaterials: 'Hârtie, mobilier',
      ignitionSources: 'Instalația electrică',
      fireRiskEquipment: 'Calculatoare, imprimante',
      specificMeasures: null,
    },
  ],
  responsiblePersons: [
    {
      fullName: 'Florin Cristian TALOȘ',
      jobTitle: 'Administrator',
      roles: [
        'workplace_manager',
        'first_aid',
        'risk_evaluation_team',
        'imminent_danger',
        'fire_safety_coordinator',
      ],
      currentEmployee: false,
      workplaceId: null,
    },
    {
      fullName: 'Ioana PETRE',
      jobTitle: 'Șef de echipă',
      roles: ['workplace_manager', 'first_aid', 'imminent_danger', 'fire_intervention_leader'],
      currentEmployee: true,
      workplaceId: workshopId,
    },
  ],
  jobPositions: [
    {
      id: '5d0f1a9e-2a6b-4c3d-8e7f-1a2b3c4d5e6f',
      name: 'Contabil',
      staffCategory: 'technical_administrative',
      workZone: 'Birou',
      activities: null,
      currentEmployeeCount: 1,
      trainingIntervalMonths: null,
      needsProtectiveEquipment: false,
      needsInstructions: true,
      instructions: [
        {
          moduleId: 'a0a0a0a0-0000-4000-8000-000000000002',
          title: 'Activități de birou',
          group: 'work_activity',
          version: {
            id: 'b0b0b0b0-0000-4000-8000-000000000002',
            number: 1,
            createdAt: '2026-09-26T10:00:00+00:00',
          },
        },
      ],
      equipment: [],
    },
    {
      id: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
      name: 'Sudor ',
      staffCategory: 'execution',
      workZone: null,
      activities: 'Sudură electrică și autogenă.',
      currentEmployeeCount: 5,
      trainingIntervalMonths: 2,
      needsProtectiveEquipment: true,
      needsInstructions: true,
      instructions: [
        {
          moduleId: 'a0a0a0a0-0000-4000-8000-000000000001',
          title: 'Sudură oxiacetilenică',
          group: 'work_equipment',
          version: {
            id: 'b0b0b0b0-0000-4000-8000-000000000001',
            number: 3,
            createdAt: '2026-09-25T08:30:00+00:00',
          },
        },
        {
          moduleId: 'a0a0a0a0-0000-4000-8000-000000000002',
          title: 'Activități de birou',
          group: 'work_activity',
          version: {
            id: 'b0b0b0b0-0000-4000-8000-000000000002',
            number: 1,
            createdAt: '2026-09-26T10:00:00+00:00',
          },
        },
      ],
      equipment: [
        {
          risk: 'Radiații, împroșcare (față, ochi)',
          item: 'Mască de sudură',
          quantity: 1,
          durationMonths: 24,
          allocation: 'section_inventory',
        },
        {
          risk: 'Căldură, foc (mâini)',
          item: 'Mănuși de sudor',
          quantity: 2,
          durationMonths: 1,
          allocation: 'personal_inventory',
        },
        {
          risk: 'Pulberi',
          item: 'Mască de unică folosință',
          quantity: 50,
          durationMonths: null,
          allocation: 'consumable',
        },
      ],
    },
  ],
  staffCategoriesInUse: ['technical_administrative', 'execution'],
  currentEmployeeCount: 6,
  workersRepresentativeDecisionGenerated: false,
  ownInstructions: {
    revisionId: 'd0d0d0d0-0000-4000-8000-000000000001',
    revisionNumber: 2,
    annexes: [
      {
        moduleId: 'a0a0a0a0-0000-4000-8000-000000000002',
        versionId: 'b0b0b0b0-0000-4000-8000-000000000002',
        title: 'Activități de birou',
        articleCount: 12,
      },
      {
        moduleId: 'a0a0a0a0-0000-4000-8000-000000000001',
        versionId: 'b0b0b0b0-0000-4000-8000-000000000001',
        title: 'Sudură oxiacetilenică',
        articleCount: 31,
      },
    ],
  },
  riskEvaluations: [
    {
      id: 'e0e0e0e0-0000-4000-8000-000000000003',
      kind: 'sensitive_groups',
      jobPositionId: null,
      name: null,
      ...sensitiveGroupsEvaluation,
    },
    {
      id: 'e0e0e0e0-0000-4000-8000-000000000002',
      kind: 'job_position',
      jobPositionId: '7c9e6679-7425-40de-944b-e07fc1f90ae7',
      name: null,
      ...workshopEvaluation,
      workTask: null,
      exposedPersons: null,
    },
    {
      id: 'e0e0e0e0-0000-4000-8000-000000000001',
      kind: 'job_position',
      jobPositionId: '5d0f1a9e-2a6b-4c3d-8e7f-1a2b3c4d5e6f',
      name: null,
      ...officeEvaluation,
      workTask: null,
      exposedPersons: null,
    },
  ],
  fireSafety: {
    card: {
      periodicTrainingHours: 2,
      administrativeTrainingIntervalMonths: 6,
      workerTrainingIntervalMonths: 3,
      trainingFirstMonth: 2,
      trainingDayFrom: 2,
      trainingDayTo: 7,
      wasteKinds: ['deșeuri de carton, hârtie, plastic', ' deșeuri menajere '],
      wasteContractor: 'S.C. ECO COLECT S.R.L.',
    },
    equipment: [
      {
        workplaceId: workshopId,
        kind: 'extinguisher',
        agent: 'powder',
        capacity: 6,
        wheeled: false,
      },
      { workplaceId: workshopId, kind: 'extinguisher', agent: 'co2', capacity: 5, wheeled: false },
      {
        workplaceId: workshopId,
        kind: 'extinguisher',
        agent: 'powder',
        capacity: 50,
        wheeled: true,
      },
      {
        workplaceId: workshopId,
        kind: 'extinguisher',
        agent: 'powder',
        capacity: 6,
        wheeled: false,
      },
      { workplaceId: workshopId, kind: 'sand_box', agent: null, capacity: null, wheeled: false },
      { workplaceId: officeId, kind: 'fire_blanket', agent: null, capacity: null, wheeled: false },
      { workplaceId: officeId, kind: 'extinguisher', agent: 'foam', capacity: 9, wheeled: false },
    ],
    installations: [
      { workplaceId: workshopId, kind: 'exterior_hydrants', description: 'Doi hidranți în curte' },
      { workplaceId: officeId, kind: 'detection_alarm', description: null },
      { workplaceId: officeId, kind: 'interior_hydrants', description: 'Câte unul pe nivel' },
    ],
  },
};
