// CAEN Rev. 3 classes (four-digit activity codes) per INS Order 377/2024, in force since 1 January 2025.
// Generated from the public nomenclature; names use comma-below diacritics.

export interface CaenClass {
  code: string;
  name: string;
}

export const caenClasses: readonly CaenClass[] = [
  {
    code: '0111',
    name: 'Cultivarea cerealelor (excluzând orezul), plantelor leguminoase și a plantelor oleaginoase',
  },
  { code: '0112', name: 'Cultivarea orezului' },
  {
    code: '0113',
    name: 'Cultivarea legumelor și a pepenilor, a rădăcinoaselor și tuberculiferelor',
  },
  { code: '0114', name: 'Cultivarea trestiei de zahăr' },
  { code: '0115', name: 'Cultivarea tutunului' },
  { code: '0116', name: 'Cultivarea plantelor pentru fibre textile' },
  { code: '0119', name: 'Cultivarea altor plante din culturi nepermanente' },
  { code: '0121', name: 'Cultivarea strugurilor' },
  { code: '0122', name: 'Cultivarea fructelor tropicale și subtropicale' },
  { code: '0123', name: 'Cultivarea fructelor citrice' },
  { code: '0124', name: 'Cultivarea fructelor semințoase și sâmburoase' },
  {
    code: '0125',
    name: 'Cultivarea altor pomi fructiferi, a arbuștilor fructiferi, căpșunilor și a nuciferelor',
  },
  { code: '0126', name: 'Cultivarea fructelor oleaginoase' },
  { code: '0127', name: 'Cultivarea plantelor pentru prepararea băuturilor' },
  {
    code: '0128',
    name: 'Cultivarea condimentelor, plantelor aromatice, medicinale și a plantelor de uz farmaceutic',
  },
  { code: '0129', name: 'Cultivarea altor plante permanente' },
  { code: '0130', name: 'Cultivarea plantelor pentru înmulțire' },
  { code: '0141', name: 'Creșterea bovinelor de lapte' },
  { code: '0142', name: 'Creșterea altor bovine' },
  { code: '0143', name: 'Creșterea cailor și a altor cabaline' },
  { code: '0144', name: 'Creșterea cămilelor și a camelidelor' },
  { code: '0145', name: 'Creșterea ovinelor și caprinelor' },
  { code: '0146', name: 'Creșterea porcinelor' },
  { code: '0147', name: 'Creșterea păsărilor' },
  { code: '0148', name: 'Creșterea altor animale' },
  {
    code: '0150',
    name: 'Activități în ferme mixte (cultura vegetală combinată cu creșterea animalelor)',
  },
  { code: '0161', name: 'Activități auxiliare pentru producția vegetală' },
  { code: '0162', name: 'Activități auxiliare pentru creșterea animalelor' },
  { code: '0163', name: 'Activități după recoltare și pregătirea semințelor' },
  {
    code: '0170',
    name: 'Vânătoare, capturarea cu capcane a vânatului și activități de servicii anexe vânătorii',
  },
  { code: '0210', name: 'Silvicultură și alte activități forestiere' },
  { code: '0220', name: 'Exploatarea forestieră' },
  { code: '0230', name: 'Colectarea produselor forestiere nelemnoase din flora spontană' },
  { code: '0240', name: 'Activități de servicii anexe silviculturii' },
  { code: '0311', name: 'Pescuitul maritim' },
  { code: '0312', name: 'Pescuitul în ape dulci' },
  { code: '0321', name: 'Acvacultura maritimă' },
  { code: '0322', name: 'Acvacultura în ape dulci' },
  { code: '0330', name: 'Activități anexe pescuitului și acvaculturii' },
  { code: '0510', name: 'Extracția cărbunelui superior (PCS=>23865 kJ/kg)' },
  { code: '0520', name: 'Extracția cărbunelui inferior (PCS<23865 kJ/kg)' },
  { code: '0610', name: 'Extracția petrolului brut' },
  { code: '0620', name: 'Extracția gazelor naturale' },
  { code: '0710', name: 'Extracția minereurilor feroase' },
  { code: '0721', name: 'Extracția minereurilor de uraniu și toriu' },
  { code: '0729', name: 'Extracția altor minereuri metalifere neferoase' },
  {
    code: '0811',
    name: 'Extracția pietrei ornamentale și a pietrei pentru construcții, extracția pietrei calcaroase, ghipsului, cretei și a ardeziei',
  },
  { code: '0812', name: 'Extracția pietrișului și nisipului; extracția argilei și caolinului' },
  {
    code: '0891',
    name: 'Extracția mineralelor pentru industria chimică și a îngrășămintelor naturale',
  },
  { code: '0892', name: 'Extracția turbei' },
  { code: '0893', name: 'Extracția sării' },
  { code: '0899', name: 'Alte activități extractive n.c.a.' },
  {
    code: '0910',
    name: 'Activități de servicii anexe extracției petrolului brut și gazelor naturale',
  },
  { code: '0990', name: 'Activități de servicii anexe pentru extracția mineralelor' },
  { code: '1011', name: 'Prelucrarea și conservarea cărnii' },
  { code: '1012', name: 'Prelucrarea și conservarea cărnii de pasăre' },
  { code: '1013', name: 'Fabricarea produselor din carne (inclusiv din carne de pasăre)' },
  { code: '1020', name: 'Prelucrarea și conservarea peștelui, crustaceelor și moluștelor' },
  { code: '1031', name: 'Prelucrarea și conservarea cartofilor' },
  { code: '1032', name: 'Fabricarea sucurilor de fructe și legume' },
  { code: '1039', name: 'Prelucrarea și conservarea fructelor și legumelor n.c.a.' },
  { code: '1041', name: 'Fabricarea uleiurilor și grăsimilor' },
  { code: '1042', name: 'Fabricarea margarinei și a altor produse comestibile similare' },
  { code: '1051', name: 'Fabricarea produselor lactate și a brânzeturilor' },
  { code: '1052', name: 'Fabricarea înghețatei' },
  { code: '1061', name: 'Fabricarea produselor de morărit' },
  { code: '1062', name: 'Fabricarea amidonului și a produselor din amidon' },
  {
    code: '1071',
    name: 'Fabricarea pâinii; fabricarea prăjiturilor și a produselor proaspete de patiserie',
  },
  {
    code: '1072',
    name: 'Fabricarea biscuiților și pișcoturilor; fabricarea prăjiturilor și a produselor conservate de patiserie',
  },
  {
    code: '1073',
    name: 'Fabricarea macaroanelor, tăițeilor, cuș-cuș-ului și a altor produse făinoase similar',
  },
  { code: '1081', name: 'Fabricarea zahărului' },
  { code: '1082', name: 'Fabricarea produselor din cacao, a ciocolatei și a produselor zaharoase' },
  { code: '1083', name: 'Prelucrarea ceaiului și cafelei' },
  { code: '1084', name: 'Fabricarea condimentelor și ingredientelor' },
  { code: '1085', name: 'Fabricarea de mâncărururi preparate' },
  { code: '1086', name: 'Fabricarea preparatelor alimentare omogenizate și alimentelor dietetice' },
  { code: '1089', name: 'Fabricarea altor produse alimentare n.c.a.' },
  { code: '1091', name: 'Fabricarea preparatelor pentru hrana animalelor de fermă' },
  { code: '1092', name: 'Fabricarea preparatelor pentru hrana animalelor de companie' },
  { code: '1101', name: 'Distilarea, rafinarea și mixarea băuturilor alcoolice' },
  { code: '1102', name: 'Fabricarea vinurilor din struguri' },
  { code: '1103', name: 'Fabricarea cidrului și a altor vinuri din fructe' },
  { code: '1104', name: 'Fabricarea altor băuturi nedistilate, obținute prin fermentare' },
  { code: '1105', name: 'Fabricarea berii' },
  { code: '1106', name: 'Fabricarea malțului' },
  {
    code: '1107',
    name: 'Producția de băuturi răcoritoare nealcoolice; producția de ape minerale și alte ape îmbuteliate',
  },
  { code: '1200', name: 'Fabricarea produselor din tutun' },
  { code: '1310', name: 'Pregătirea fibrelor și filarea fibrelor textile' },
  { code: '1320', name: 'Producția de țesături' },
  { code: '1330', name: 'Finisarea materialelor textile' },
  { code: '1391', name: 'Fabricarea de metraje prin tricotare sau croșetare' },
  {
    code: '1392',
    name: 'Fabricarea de articole confecționate din textile (excluzând îmbrăcămintea și lenjeria de corp)',
  },
  { code: '1393', name: 'Fabricarea de covoare și mochete' },
  { code: '1394', name: 'Fabricarea de odgoane, frânghii, sfori și plase' },
  {
    code: '1395',
    name: 'Fabricarea de textile nețesute și articole din acestea, cu excepția confecțiilor de îmbrăcăminte',
  },
  { code: '1396', name: 'Fabricarea de articole tehnice și industriale din textile' },
  { code: '1399', name: 'Fabricarea altor articole textile n.c.a.' },
  { code: '1410', name: 'Fabricarea articolelor de îmbrăcăminte prin tricotare sau croșetare' },
  { code: '1421', name: 'Fabricarea articolelor de îmbrăcăminte' },
  { code: '1422', name: 'Fabricarea de articole de lenjerie de corp' },
  { code: '1423', name: 'Fabricarea de articole de îmbrăcăminte pentru lucru' },
  { code: '1424', name: 'Fabricarea articolelor de îmbrăcăminte din piele și blană' },
  { code: '1429', name: 'Fabricarea altor articole de îmbrăcăminte și accesorii n.c.a.' },
  { code: '1511', name: 'Tăbăcirea și finisarea pieilor; prepararea și vopsirea blănurilor' },
  {
    code: '1512',
    name: 'Fabricarea articolelor de voiaj și marochinărie și a articolelor de harnașament',
  },
  { code: '1520', name: 'Fabricarea încălțămintei' },
  { code: '1611', name: 'Tăierea și rindeluirea lemnului' },
  { code: '1612', name: 'Prelucrarea și finisarea lemnului' },
  { code: '1621', name: 'Fabricarea de furnire și a panourilor din lemn' },
  { code: '1622', name: 'Fabricarea parchetului asamblat în panouri' },
  { code: '1623', name: 'Fabricarea altor elemente de dulgherie și tâmplărie, pentru construcții' },
  { code: '1624', name: 'Fabricarea ambalajelor din lemn' },
  { code: '1625', name: 'Fabricarea de uși și ferestre din lemn' },
  { code: '1626', name: 'Fabricarea de combustibili solizi din biomasă vegetală' },
  { code: '1627', name: 'Finisarea articolelor din lemn' },
  {
    code: '1628',
    name: 'Fabricarea altor produse din lemn; fabricarea articolelor din plută, paie și din alte materiale vegetale împletite',
  },
  { code: '1711', name: 'Fabricarea celulozei' },
  { code: '1712', name: 'Fabricarea hârtiei și cartonului' },
  {
    code: '1721',
    name: 'Fabricarea hârtiei și cartonului ondulat și a ambalajelor din hârtie și carton',
  },
  {
    code: '1722',
    name: 'Fabricarea produselor de uz gospodăresc și sanitar, din hârtie sau carton',
  },
  { code: '1723', name: 'Fabricarea articolelor de papetărie' },
  { code: '1724', name: 'Fabricarea tapetului' },
  { code: '1725', name: 'Fabricarea altor articole din hârtie și carton n.c.a.' },
  { code: '1811', name: 'Tipărirea ziarelor' },
  { code: '1812', name: 'Alte activități de tipărire n.c.a.' },
  { code: '1813', name: 'Servicii pregătitoare pentru pretipărire' },
  { code: '1814', name: 'Legătorie și servicii conexe' },
  { code: '1820', name: 'Reproducerea înregistrărilor' },
  { code: '1910', name: 'Fabricarea produselor de cocserie' },
  { code: '1920', name: 'Fabricarea produselor obținute din prelucrarea țițeiului' },
  { code: '2011', name: 'Fabricarea gazelor industriale' },
  { code: '2012', name: 'Fabricarea coloranților și a pigmenților' },
  { code: '2013', name: 'Fabricarea altor produse chimice anorganice, de bază' },
  { code: '2014', name: 'Fabricarea altor produse chimice organice, de bază' },
  { code: '2015', name: 'Fabricarea îngrășămintelor și produselor azotoase' },
  { code: '2016', name: 'Fabricarea materialelor plastice în forme primare' },
  { code: '2017', name: 'Fabricarea cauciucului sintetic în forme primare' },
  { code: '2020', name: 'Fabricarea pesticidelor și a altor produse agrochimice' },
  { code: '2030', name: 'Fabricarea vopselelor, lacurilor, cernelii tipografice și masticurilor' },
  { code: '2041', name: 'Fabricarea săpunurilor, detergenților și a produselor de întreținere' },
  { code: '2042', name: 'Fabricarea parfumurilor și a produselor cosmetice (de toaletă)' },
  { code: '2051', name: 'Fabricarea biocombustibililor lichizi' },
  { code: '2059', name: 'Fabricarea altor produse chimice n.c.a.' },
  { code: '2060', name: 'Fabricarea fibrelor sintetice și artificiale' },
  { code: '2110', name: 'Fabricarea produselor farmaceutice de bază' },
  { code: '2120', name: 'Fabricarea preparatelor farmaceutice' },
  {
    code: '2211',
    name: 'Fabricarea anvelopelor și a camerelor de aer; reșaparea și refacerea anvelopelor',
  },
  { code: '2212', name: 'Fabricarea altor produse din cauciuc' },
  {
    code: '2221',
    name: 'Fabricarea plăcilor, foliilor, tuburilor și profilelor din material plastic',
  },
  { code: '2222', name: 'Fabricarea articolelor de ambalaj din material plastic' },
  { code: '2223', name: 'Fabricarea de uși și ferestre din material plastic' },
  { code: '2224', name: 'Fabricarea articolelor din material plastic pentru construcții' },
  { code: '2225', name: 'Prelucrarea și finisarea articolelor din material plastic' },
  { code: '2226', name: 'Fabricarea altor produse din material plastic' },
  { code: '2311', name: 'Fabricarea sticlei plate' },
  { code: '2312', name: 'Prelucrarea și fasonarea sticlei plate' },
  { code: '2313', name: 'Fabricarea articolelor din sticlă' },
  { code: '2314', name: 'Fabricarea fibrelor din sticlă' },
  { code: '2315', name: 'Fabricarea de sticlărie tehnică' },
  { code: '2320', name: 'Fabricarea de produse refractare' },
  { code: '2331', name: 'Fabricarea plăcilor și dalelor din ceramică' },
  {
    code: '2332',
    name: 'Fabricarea cărămizilor, țiglelor și altor produse pentru construcții, din argilă arsă',
  },
  { code: '2341', name: 'Fabricarea articolelor ceramice pentru uz gospodăresc și ornamental' },
  { code: '2342', name: 'Fabricarea de obiecte sanitare din ceramică' },
  { code: '2343', name: 'Fabricarea izolatorilor și pieselor izolante din ceramică' },
  { code: '2344', name: 'Fabricarea altor produse tehnice din ceramică' },
  { code: '2345', name: 'Fabricarea altor produse ceramice n.c.a.' },
  { code: '2351', name: 'Fabricarea cimentului' },
  { code: '2352', name: 'Fabricarea varului și ipsosului' },
  { code: '2361', name: 'Fabricarea produselor din beton pentru construcții' },
  { code: '2362', name: 'Fabricarea produselor din ipsos pentru construcții' },
  { code: '2363', name: 'Fabricarea betonului' },
  { code: '2364', name: 'Fabricarea mortarului' },
  { code: '2365', name: 'Fabricarea produselor din azbociment' },
  { code: '2366', name: 'Fabricarea altor articole din beton, ciment și ipsos' },
  { code: '2370', name: 'Tăierea, fasonarea și finisarea pietrei' },
  { code: '2391', name: 'Fabricarea de produse abrazive' },
  { code: '2399', name: 'Fabricarea altor produse din minerale nemetalice, n.c.a.' },
  { code: '2410', name: 'Producția de metale feroase sub forme primare și de feroaliaje' },
  {
    code: '2420',
    name: 'Producția de tuburi, țevi, profile tubulare și accesorii pentru acestea, din oțel',
  },
  { code: '2431', name: 'Tragere la rece a barelor' },
  { code: '2432', name: 'Laminare la rece a benzilor înguste' },
  { code: '2433', name: 'Producția de profile obținute la rece' },
  { code: '2434', name: 'Trefilarea firelor la rece' },
  { code: '2441', name: 'Producția metalelor prețioase' },
  { code: '2442', name: 'Metalurgia aluminiului' },
  { code: '2443', name: 'Producția plumbului, zincului și cositorului' },
  { code: '2444', name: 'Metalurgia cuprului' },
  { code: '2445', name: 'Producția altor metale neferoase' },
  { code: '2446', name: 'Prelucrarea combustibililor nucleari' },
  { code: '2451', name: 'Turnarea fontei' },
  { code: '2452', name: 'Turnarea oțelului' },
  { code: '2453', name: 'Turnarea metalelor neferoase ușoare' },
  { code: '2454', name: 'Turnarea altor metale neferoase' },
  {
    code: '2511',
    name: 'Fabricarea de construcții metalice și părți componente ale structurilor metalice',
  },
  { code: '2512', name: 'Fabricarea de uși și ferestre din metal' },
  {
    code: '2521',
    name: 'Producția de radiatoare și cazane pentru încălzire central; producția de generatoare de abur și boilere',
  },
  { code: '2522', name: 'Producția de rezervoare, cisterne și containere metalice' },
  { code: '2530', name: 'Fabricarea armamentului și muniției' },
  {
    code: '2540',
    name: 'Fabricarea produselor metalice obținute prin deformare plastică; metalurgia pulberilor',
  },
  { code: '2551', name: 'Acoperirea metalelor' },
  { code: '2552', name: 'Tratamente termice ale metalelor' },
  { code: '2553', name: 'Operațiuni de mecanică generală' },
  { code: '2561', name: 'Fabricarea produselor de tăiat' },
  { code: '2562', name: 'Fabricarea articolelor de feronerie' },
  { code: '2563', name: 'Fabricarea uneltelor' },
  { code: '2591', name: 'Fabricarea de recipienți, containere și alte produse similare din oțel' },
  { code: '2592', name: 'Fabricarea ambalajelor metalice ușoare' },
  {
    code: '2593',
    name: 'Fabricarea articolelor din fire metalice; fabricarea de lanțuri și arcuri',
  },
  {
    code: '2594',
    name: 'Fabricarea de șuruburi, buloane și alte articole filetate; fabricarea de nituri și șaibe',
  },
  { code: '2599', name: 'Fabricarea altor articole din metal n.c.a.' },
  { code: '2611', name: 'Fabricarea componentelor electronice' },
  { code: '2612', name: 'Fabricarea subansamblurilor electronice (module)' },
  { code: '2620', name: 'Fabricarea calculatoarelor și a echipamentelor periferice' },
  { code: '2630', name: 'Fabricarea echipamentelor de comunicații' },
  { code: '2640', name: 'Fabricarea produselor electronice de larg consum' },
  {
    code: '2651',
    name: 'Fabricarea de instrumente și dispozitive pentru măsură, verificare, control, navigație',
  },
  { code: '2652', name: 'Producția de ceasuri' },
  {
    code: '2660',
    name: 'Fabricarea de echipamente pentru radiologie, electrodiagnostic și electroterapie',
  },
  {
    code: '2670',
    name: 'Fabricarea de instrumente optice, suporți magnetici și optici; fabricarea de echipamente fotografice',
  },
  { code: '2711', name: 'Fabricarea motoarelor, generatoarelor și transformatoarelor electrice' },
  { code: '2712', name: 'Fabricarea aparatelor de distribuție și control a electricității' },
  { code: '2720', name: 'Fabricarea de acumulatori și baterii' },
  { code: '2731', name: 'Fabricarea de cabluri cu fibră optică' },
  { code: '2732', name: 'Fabricarea altor fire și cabluri electrice și electronice' },
  {
    code: '2733',
    name: 'Fabricarea dispozitivelor de conexiune pentru fire și cabluri electrice și electronice',
  },
  { code: '2740', name: 'Fabricarea de echipamente electrice de iluminat' },
  { code: '2751', name: 'Fabricarea de aparate electrocasnice' },
  { code: '2752', name: 'Fabricarea de echipamente casnice neelectrice' },
  { code: '2790', name: 'Fabricarea altor echipamente electrice' },
  {
    code: '2811',
    name: 'Fabricarea de motoare și turbine (cu excepția celor pentru avioane, autovehicule și motociclete.)',
  },
  { code: '2812', name: 'Fabricarea de motoare hidraulice' },
  { code: '2813', name: 'Fabricarea de pompe și compresoare' },
  { code: '2814', name: 'Fabricarea de articole de robinetărie' },
  {
    code: '2815',
    name: 'Fabricarea lagărelor, angrenajelor, cutiilor de viteză și a elementelor mecanice de transmisie',
  },
  { code: '2821', name: 'Fabricarea cuptoarelor, furnalelor și arzătoarelor' },
  { code: '2822', name: 'Fabricarea echipamentelor de ridicat și manipulat' },
  {
    code: '2823',
    name: 'Fabricarea mașinilor și echipamentelor de birou (exceptând fabricarea calculatoarelor și a echipamentelor periferice)',
  },
  { code: '2824', name: 'Fabricarea mașinilor-unelte portabile acționate electric' },
  {
    code: '2825',
    name: 'Fabricarea echipamentelor de ventilație și frigorifice, exceptând echipamentele de uz casnic',
  },
  { code: '2829', name: 'Fabricarea altor mașini și utilaje de utilizare generală n.c.a.' },
  {
    code: '2830',
    name: 'Fabricarea masinilor și utilajelor pentru agricultură și exploatări forestiere',
  },
  {
    code: '2841',
    name: 'Fabricarea utilajelor și a mașinilor-unelte pentru prelucrarea metalului',
  },
  { code: '2842', name: 'Fabricarea altor mașini-unelte n.c.a.' },
  { code: '2891', name: 'Fabricarea utilajelor pentru metalurgie' },
  { code: '2892', name: 'Fabricarea utilajelor pentru extracție și construcții' },
  {
    code: '2893',
    name: 'Fabricarea utilajelor pentru prelucrarea produselor alimentare, băuturilor și tutunului',
  },
  {
    code: '2894',
    name: 'Fabricarea utilajelor pentru industria textilă, a îmbrăcămintei și a pielăriei',
  },
  { code: '2895', name: 'Fabricarea utilajelor pentru industria hârtiei și cartonului' },
  {
    code: '2896',
    name: 'Fabricarea utilajelor pentru prelucrarea maselor plastice și a cauciucului',
  },
  {
    code: '2897',
    name: 'Fabricarea mașinilor și utilajelor pentru fabricația aditivă (care utilizează tehnologia de fabricație aditivă)',
  },
  { code: '2899', name: 'Fabricarea altor mașini și utilaje specifice n.c.a.' },
  { code: '2910', name: 'Fabricarea autovehiculelor de transport rutier' },
  {
    code: '2920',
    name: 'Producția de caroserii pentru autovehicule; fabricarea de remorci și semiremorci',
  },
  {
    code: '2931',
    name: 'Fabricarea de echipamente electrice și electronice pentru autovehicule și pentru motoare de autovehicule',
  },
  {
    code: '2932',
    name: 'Fabricarea altor piese și accesorii pentru autovehicule și pentru motoare de autovehicule',
  },
  { code: '3011', name: 'Construcția de nave civile și structuri plutitoare' },
  { code: '3012', name: 'Construcția de ambarcațiuni sportive și de agrement' },
  { code: '3013', name: 'Construcția de nave și vase militare' },
  { code: '3020', name: 'Fabricarea materialului rulant' },
  { code: '3031', name: 'Fabricarea de aeronave și nave spațiale, civile' },
  { code: '3032', name: 'Fabricarea de aeronave și nave spațiale, militare' },
  { code: '3040', name: 'Fabricarea vehiculelor militare de luptă' },
  { code: '3091', name: 'Fabricarea de motociclete' },
  { code: '3092', name: 'Fabricarea de biciclete și de de vehicule pentru invalizi' },
  { code: '3099', name: 'Fabricarea altor mijloace de transport n.c.a.' },
  { code: '3100', name: 'Fabricarea de mobilă' },
  { code: '3211', name: 'Baterea monedelor' },
  {
    code: '3212',
    name: 'Fabricarea bijuteriilor și articolelor similare din metale și pietre prețioase',
  },
  { code: '3213', name: 'Fabricarea imitațiilor de bijuterii și articole similare' },
  { code: '3220', name: 'Fabricarea instrumentelor muzicale' },
  { code: '3230', name: 'Fabricarea articolelor pentru sport' },
  { code: '3240', name: 'Fabricarea jocurilor și jucăriilor' },
  {
    code: '3250',
    name: 'Fabricarea de dispozitive, aparate și instrumente medicale stomatologice',
  },
  { code: '3291', name: 'Fabricarea măturilor și periilor' },
  { code: '3299', name: 'Fabricarea altor produse manufacturiere n.c.a.' },
  { code: '3311', name: 'Repararea și întreținerea articolelor fabricate din metal' },
  { code: '3312', name: 'Repararea și întreținerea mașinilor' },
  { code: '3313', name: 'Repararea și întreținerea echipamentelor electronice și optice' },
  { code: '3314', name: 'Repararea și întreținerea echipamentelor electrice' },
  { code: '3315', name: 'Repararea și întreținerea navelor și bărcilor, civile' },
  { code: '3316', name: 'Repararea și întreținerea aeronavelor și navelor spațiale, civile' },
  { code: '3317', name: 'Repararea și întreținerea altor echipamente civile de transport n.c.a.' },
  {
    code: '3318',
    name: 'Repararea și întreținerea vehiculelor militare de luptă, a navelor, vaselor, aeronavelor și navelor spațiale, militare',
  },
  { code: '3319', name: 'Repararea și întreținerea altor echipamente' },
  { code: '3320', name: 'Instalarea mașinilor și echipamentelor industriale' },
  { code: '3511', name: 'Producția de energie electrică din resurse neregenerabile' },
  { code: '3512', name: 'Producția de energie electrică din resurse regenerabile' },
  { code: '3513', name: 'Transportul energiei electrice' },
  { code: '3514', name: 'Distribuția energiei electrice' },
  { code: '3515', name: 'Comercializarea energiei electrice' },
  { code: '3516', name: 'Depozitarea energiei electrice' },
  { code: '3521', name: 'Producția gazelor' },
  { code: '3522', name: 'Distribuția combustibililor gazoși, prin conducte' },
  { code: '3523', name: 'Comercializarea combustibililor gazoși, prin conducte' },
  { code: '3524', name: 'Depozitarea gazelor, ca parte a serviciilor de furnizare' },
  { code: '3530', name: 'Furnizarea de abur și aer condiționat' },
  {
    code: '3540',
    name: 'Activități ale agenților și brokerilor din domeniul energiei electrice și a gazelor naturale',
  },
  { code: '3600', name: 'Captarea, tratarea și distribuția apei' },
  { code: '3700', name: 'Colectarea și epurarea apelor uzate' },
  { code: '3811', name: 'Colectarea deșeurilor nepericuloase' },
  { code: '3812', name: 'Colectarea deșeurilor periculoase' },
  { code: '3821', name: 'Recuperarea materialelor reciclabile' },
  {
    code: '3822',
    name: 'Producția de energie (electrică sau termică) prin tratarea deșeurilor (inclusiv prin incinerare)',
  },
  { code: '3823', name: 'Alte activități de tartare a deșeurilor' },
  { code: '3831', name: 'Incinerarea deșeurilor fără producție de energie' },
  {
    code: '3832',
    name: 'Activități ale gropilor de gunoi sau a depozitelor permanente de deșeuri',
  },
  { code: '3833', name: 'Alte activități de eliminare a deșeurilor' },
  { code: '3900', name: 'Activități și servicii de decontaminare' },
  { code: '4100', name: 'Lucrări de construcții a clădirilor rezidențiale și nerezidențiale' },
  { code: '4211', name: 'Lucrări de construcții a drumurilor și autostrăzilor' },
  { code: '4212', name: 'Lucrări de construcții a căilor ferate de suprafață și subterane.' },
  { code: '4213', name: 'Construcția de poduri și tuneluri' },
  { code: '4221', name: 'Lucrări de construcții a proiectelor utilitare pentru fluide' },
  {
    code: '4222',
    name: 'Lucrări de construcții a proiectelor utilitare pentru electricitate și telecomunicații',
  },
  { code: '4291', name: 'Construcții hidrotehnice' },
  { code: '4299', name: 'Lucrări de construcții a altor proiecte inginerești n.c.a.' },
  { code: '4311', name: 'Lucrări de demolare a construcțiilor' },
  { code: '4312', name: 'Lucrări de pregătire a terenului' },
  { code: '4313', name: 'Lucrări de foraj și sondaj pentru construcții' },
  { code: '4321', name: 'Lucrări de instalații electrice' },
  { code: '4322', name: 'Lucrări de instalații sanitare, de încălzire și de aer condiționat' },
  { code: '4323', name: 'Lucrări de izolații' },
  { code: '4324', name: 'Alte lucrări de instalații pentru construcții' },
  { code: '4331', name: 'Lucrări de ipsoserie' },
  { code: '4332', name: 'Lucrări de tâmplărie și dulgherie' },
  { code: '4333', name: 'Lucrări de pardosire și placare a pereților' },
  { code: '4334', name: 'Lucrări de vopsitorie, zugrăveli și montări de geamuri' },
  { code: '4335', name: 'Alte lucrări de finisare' },
  { code: '4341', name: 'Lucrări de învelitori, șarpante și terase la construcții' },
  { code: '4342', name: 'Alte lucrări speciale de construcții pentru clădiri' },
  { code: '4350', name: 'Lucrări speciale de construcții pentru proiecte de geniu civil' },
  { code: '4360', name: 'Servicii de intermediere pentru lucrări speciale de construcții' },
  { code: '4391', name: 'Activități de zidărie' },
  { code: '4399', name: 'Alte lucrări speciale de construcții n.c.a.' },
  {
    code: '4611',
    name: 'Intermedieri în comerțul cu materii prime agricole, animale vii, materii prime textile și cu semifabricate',
  },
  {
    code: '4612',
    name: 'Intermedieri în comerțul cu combustibili, minereuri, metale și produse chimice pentru industrie',
  },
  { code: '4613', name: 'Intermedieri în comerțul cu material lemnos și materiale de construcții' },
  {
    code: '4614',
    name: 'Intermedieri în comerțul cu mașini, echipamente industriale, nave și avioane',
  },
  { code: '4615', name: 'Intermedieri în comerțul cu mobilă, articole de menaj și de fierărie' },
  {
    code: '4616',
    name: 'Intermedieri în comerțul cu textile, confecții din blană, încălțăminte și articole din piele',
  },
  { code: '4617', name: 'Intermedieri în comerțul cu produse alimentare, băuturi și tutun' },
  {
    code: '4618',
    name: 'Intermedieri în comerțul specializat în vânzarea produselor cu caracter specific, n.c.a.',
  },
  { code: '4619', name: 'Intermedieri în comerțul cu produse diverse' },
  {
    code: '4621',
    name: 'Comerț cu ridicata al cerealelor, semințelor, furajelor și tutunului neprelucrat',
  },
  { code: '4622', name: 'Comerț cu ridicata al florilor și al plantelor' },
  { code: '4623', name: 'Comerț cu ridicata al animalelor vii' },
  {
    code: '4624',
    name: 'Comerț cu ridicata al blănurilor, pieilor brute și al pieilor prelucrate',
  },
  { code: '4631', name: 'Comerț cu ridicata al fructelor și legumelor' },
  {
    code: '4632',
    name: 'Comerț cu ridicata al cărnii și produselor din carne, pește și produse din pește, crustacee și moluște',
  },
  {
    code: '4633',
    name: 'Comerț cu ridicata al produselor lactate, ouălor, uleiurilor și grăsimilor comestibile',
  },
  { code: '4634', name: 'Comerț cu ridicata al băuturilor' },
  { code: '4635', name: 'Comerț cu ridicata al produselor din tutun' },
  { code: '4636', name: 'Comerț cu ridicata al zahărului, ciocolatei și produselor zaharoase' },
  { code: '4637', name: 'Comerț cu ridicata cu cafea, ceai, cacao și condimente' },
  { code: '4638', name: 'Comerț cu ridicata specializat al altor alimente' },
  {
    code: '4639',
    name: 'Comerț cu ridicata nespecializat de produse alimentare, băuturi și tutun',
  },
  { code: '4641', name: 'Comerț cu ridicata al produselor textile' },
  { code: '4642', name: 'Comerț cu ridicata al îmbrăcămintei și încălțămintei' },
  {
    code: '4643',
    name: 'Comerț cu ridicata al aparatelor electrice de uz gospodăresc, al aparatelor de radio și televizoarelor',
  },
  {
    code: '4644',
    name: 'Comerț cu ridicata al produselor din ceramică, sticlărie, și produse de întreținere',
  },
  { code: '4645', name: 'Comerț cu ridicata al produselor cosmetice și de parfumerie' },
  { code: '4646', name: 'Comerț cu ridicata al produselor farmaceutice și medicale' },
  {
    code: '4647',
    name: 'Comerț cu ridicata al mobilei (inclusiv de birou și pentru magazine), covoarelor și a articolelor de iluminat',
  },
  { code: '4648', name: 'Comerț cu ridicata al ceasurilor și bijuteriilor' },
  { code: '4649', name: 'Comerț cu ridicata al altor bunuri de uz gospodăresc' },
  { code: '4650', name: 'Comerț cu ridicata al echipamentului informatic și de telecomunicații' },
  {
    code: '4661',
    name: 'Comerț cu ridicata al mașinilor agricole, echipamentelor și furniturilor',
  },
  { code: '4662', name: 'Comerț cu ridicata al mașinilor-unelte' },
  { code: '4663', name: 'Comerț cu ridicata al mașinilor pentru industria minieră și construcții' },
  { code: '4664', name: 'Comerț cu ridicata al altor mașini și echipamente' },
  { code: '4671', name: 'Comerț cu ridicata al autovehiculelor' },
  { code: '4672', name: 'Comerț cu ridicata al pieselor și accesoriilor pentru autovehicule' },
  {
    code: '4673',
    name: 'Comerț cu ridicata al motocicletelor; comerț cu ridicata al pieselor și accesoriilor pentru motociclete',
  },
  {
    code: '4681',
    name: 'Comerț cu ridicata al combustibililor solizi, lichizi și gazoși și al produselor derivate',
  },
  { code: '4682', name: 'Comerț cu ridicata al metalelor și minereurilor metalice' },
  {
    code: '4683',
    name: 'Comerț cu ridicata al materialului lemnos și a materialelor de construcție și echipamentelor sanitare',
  },
  {
    code: '4684',
    name: 'Comerț cu ridicata al echipamentelor și furniturilor de fierărie pentru instalații sanitare și de încălzire',
  },
  { code: '4685', name: 'Comerț cu ridicata al produselor chimice' },
  { code: '4686', name: 'Comerț cu ridicata al altor produse intermediare' },
  { code: '4687', name: 'Comerț cu ridicata al deșeurilor și resturilor' },
  { code: '4689', name: 'Comerț cu ridicata specializat al altor produse n.c.a.' },
  { code: '4690', name: 'Comerț cu ridicata nespecializat' },
  {
    code: '4711',
    name: 'Comerț cu amănuntul nespecializat, cu vânzare predominantă de produse alimentare, băuturi și tutun',
  },
  {
    code: '4712',
    name: 'Comerț cu amănuntul nespecializat, cu vânzare predominantă de produse nealimentare',
  },
  { code: '4721', name: 'Comerț cu amănuntul al fructelor și legumelor proaspete' },
  { code: '4722', name: 'Comerț cu amănuntul al cărnii și al produselor din carne' },
  { code: '4723', name: 'Comerț cu amănuntul al peștelui, crustaceelor și moluștelor' },
  {
    code: '4724',
    name: 'Comerț cu amănuntul al pâinii, produselor de patiserie și produselor zaharoase',
  },
  { code: '4725', name: 'Comerț cu amănuntul al băuturilor' },
  { code: '4726', name: 'Comerț cu amănuntul al produselor din tutun' },
  { code: '4727', name: 'Comerț cu amănuntul al altor produse alimentare' },
  { code: '4730', name: 'Comerț cu amănuntul al carburanților pentru autovehicule' },
  { code: '4740', name: 'Comerț cu amănuntul al echipamentului informatic și de telecomunicații' },
  { code: '4751', name: 'Comerț cu amănuntul al textilelor' },
  {
    code: '4752',
    name: 'Comerț cu amănuntul al articolelor de fierărie, al materialelor de construcții, al articolelor din sticlă și a celor pentru vopsit',
  },
  {
    code: '4753',
    name: 'Comerț cu amănuntul al covoarelor, carpetelor, tapetelor și a altor acoperitoare de podea',
  },
  { code: '4754', name: 'Comerț cu amănuntul al articolelor și aparatelor electrocasnice' },
  {
    code: '4755',
    name: 'Comerț cu amănuntul al mobilei, al articolelor de iluminat și al altor articole de uz casnic n.c.a.',
  },
  { code: '4761', name: 'Comerț cu amănuntul al cărților' },
  { code: '4762', name: 'Comerț cu amănuntul al ziarelor și articolelor de papetărie' },
  { code: '4763', name: 'Comerț cu amănuntul al echipamentelor sportive' },
  { code: '4764', name: 'Comerț cu amănuntul al jocurilor și jucăriilor' },
  { code: '4769', name: 'Comerț cu amănuntul de bunuri culturale și recreative n.c.a.' },
  { code: '4771', name: 'Comerț cu amănuntul al îmbrăcămintei' },
  { code: '4772', name: 'Comerț cu amănuntul al încălțămintei și articolelor din piele' },
  { code: '4773', name: 'Comerț cu amănuntul al produselor farmaceutice' },
  { code: '4774', name: 'Comerț cu amănuntul al articolelor medicale și ortopedice' },
  { code: '4775', name: 'Comerț cu amănuntul al produselor cosmetice și de parfumerie' },
  {
    code: '4776',
    name: 'Comerț cu amănuntul al florilor, plantelor și semințelor; comerț cu amănuntul al animalelor de companie și a hranei pentru acestea',
  },
  { code: '4777', name: 'Comerț cu amănuntul al ceasurilor și bijuteriilor' },
  { code: '4778', name: 'Comerț cu amănuntul al altor bunuri noi' },
  { code: '4779', name: 'Comerț cu amănuntul al bunurilor de ocazie' },
  { code: '4781', name: 'Comerț cu amănuntul al autovehiculelor' },
  { code: '4782', name: 'Comerț cu amănuntul al pieselor și accesoriilor pentru autovehicule' },
  {
    code: '4783',
    name: 'Comerț cu amănuntul al motocicletelor; comerț cu amănuntul al pieselor și accesoriilor pentru motociclete',
  },
  { code: '4791', name: 'Intermedieri în comerțul cu amănuntul nespecializat' },
  { code: '4792', name: 'Intermedieri în comerțul cu amănuntul specializat' },
  { code: '4911', name: 'Transport de pasageri pe căi ferate grele/magistrale' },
  { code: '4912', name: 'Alte transporturi de pasageri pe căi ferate ușoare' },
  { code: '4920', name: 'Transporturi de marfă pe calea ferată' },
  { code: '4931', name: 'Transporturi terestre de pasageri, pe bază de grafic' },
  { code: '4932', name: 'Transporturi terestre de pasageri, ocazionale' },
  {
    code: '4933',
    name: 'Transporturi terestre de pasageri cu vehicule cu șofer, pe bază de comandă',
  },
  { code: '4934', name: 'Transporturi de pasageri cu funiculare, teleferice și schilifturi' },
  { code: '4939', name: 'Alte transporturi terestre de călători n.c.a.' },
  { code: '4941', name: 'Transporturi rutiere de mărfuri' },
  { code: '4942', name: 'Servicii de mutare' },
  { code: '4950', name: 'Transporturi prin conducte' },
  { code: '5010', name: 'Transporturi maritime și costiere de pasageri' },
  { code: '5020', name: 'Transporturi maritime și costiere de marfă' },
  { code: '5030', name: 'Transportul de pasageri pe căi navigabile interioare' },
  { code: '5040', name: 'Transportul de marfă pe căi navigabile interioare' },
  { code: '5110', name: 'Transporturi aeriene de pasageri' },
  { code: '5121', name: 'Transporturi aeriene de marfă' },
  { code: '5122', name: 'Transporturi spațiale' },
  { code: '5210', name: 'Depozitări' },
  { code: '5221', name: 'Activități de servicii anexe pentru transporturi terestre' },
  { code: '5222', name: 'Activități de servicii anexe transporturilor pe apă' },
  { code: '5223', name: 'Activități de servicii anexe transporturilor aeriene' },
  { code: '5224', name: 'Manipulări' },
  { code: '5225', name: 'Activități de servicii logistice pentru transporturi' },
  { code: '5226', name: 'Alte activități anexe transporturilor' },
  { code: '5231', name: 'Activități de intermediere pentru transportul de marfă' },
  { code: '5232', name: 'Activități de intermediere pentru transportul de pasageri' },
  {
    code: '5310',
    name: 'Activități poștale desfășurate sub obligativitatea serviciului universal',
  },
  { code: '5320', name: 'Alte activități poștale și de curier' },
  { code: '5330', name: 'Servicii de intermediere pentru activități poștale și de curier' },
  { code: '5510', name: 'Hoteluri și alte facilități de cazare similare' },
  { code: '5520', name: 'Facilități de cazare pentru vacanțe și perioade de scurtă durată' },
  { code: '5530', name: 'Parcuri pentru rulote, campinguri și tabere' },
  { code: '5540', name: 'Intermedieri pentru servicii de cazare' },
  { code: '5590', name: 'Alte servicii de cazare' },
  { code: '5611', name: 'Restaurante' },
  { code: '5612', name: 'Activități ale unităților mobile de alimentație' },
  { code: '5621', name: 'Activități de alimentație (catering) pentru evenimente' },
  { code: '5622', name: 'Alte servicii de alimentație n.c.a.' },
  { code: '5630', name: 'Baruri și alte activități de servire a băuturilor' },
  { code: '5640', name: 'Intermedieri pentru servicii de alimentație și de servire a băuturilor' },
  { code: '5811', name: 'Activități de editare a cărților' },
  { code: '5812', name: 'Activități de editare a ziarelor' },
  { code: '5813', name: 'Activități de editare a revistelor și periodicelor' },
  { code: '5819', name: 'Alte activități de editare' },
  { code: '5821', name: 'Activități de editare a jocurilor de calculator' },
  { code: '5829', name: 'Activități de editare a altor produse software' },
  {
    code: '5911',
    name: 'Activități de producție cinematografică, video și de programe de televiziune',
  },
  {
    code: '5912',
    name: 'Activități post-producție cinematografică, video și de programe de televiziune',
  },
  {
    code: '5913',
    name: 'Activități de distribuție a filmelor cinematografice, video și a programelor de televiziune',
  },
  { code: '5914', name: 'Proiecția de filme cinematografice' },
  {
    code: '5920',
    name: 'Activități de realizare a înregistrărilor audio și activități de editare muzicală',
  },
  { code: '6010', name: 'Activități radiodifuziune, activități de distribuție de programe audio' },
  {
    code: '6020',
    name: 'Activități de difuzare a programelor de televiziune, activități de distribuție de programe video',
  },
  { code: '6031', name: 'Activități ale agențiilor de știri' },
  { code: '6039', name: 'Activități de distribuție a altor conținuturi' },
  {
    code: '6110',
    name: 'Activități de telecomunicații prin rețele cu cablu, prin rețele fără cablu și prin satelit',
  },
  {
    code: '6120',
    name: 'Activități de revânzare a serviciilor de telecomunicații și servicii de intermediere pentru telecomunicații',
  },
  { code: '6190', name: 'Alte activități de telecomunicații' },
  {
    code: '6210',
    name: 'Activități de realizare a soft-ului la comandă (software orientat client)',
  },
  {
    code: '6220',
    name: 'Activități de consultanță în tehnologia informației și de management (gestiune și exploatare) a mijloacelor de calcul',
  },
  { code: '6290', name: 'Alte activități de servicii privind tehnologia informației' },
  { code: '6310', name: 'Prelucrarea datelor, administrarea paginilor web și activități conexe' },
  { code: '6391', name: 'Activități ale portalurilor web' },
  { code: '6392', name: 'Alte activități de servicii informaționale n.c. a' },
  { code: '6411', name: 'Activități ale băncii centrale (naționale)' },
  { code: '6419', name: 'Alte activități de intermedieri monetare' },
  { code: '6421', name: 'Activități ale holding-urilor' },
  { code: '6422', name: 'Activități ale canalelor de finanțare' },
  {
    code: '6431',
    name: 'Activități ale fondurilor de investiții de pe piața monetară și ale fondurilor de investiții din afara pieței monetare',
  },
  { code: '6432', name: 'Fonduri mutuale și alte entități financiare similare' },
  { code: '6491', name: 'Leasing financiar' },
  { code: '6492', name: 'Alte activități de creditare' },
  {
    code: '6499',
    name: 'Alte intermedieri financiare n.c.a., exceptând activități de asigurări și fonduri de pensii',
  },
  { code: '6511', name: 'Activități de asigurări de viață' },
  { code: '6512', name: 'Alte activități de asigurări (exceptând asigurările de viață)' },
  { code: '6520', name: 'Activități de reasigurare' },
  {
    code: '6530',
    name: 'Activități ale fondurilor de pensii (cu excepția celor din sistemul public de asigurări sociale)',
  },
  { code: '6611', name: 'Administrarea piețelor financiare' },
  { code: '6612', name: 'Activități de intermediere a tranzacțiilor financiare' },
  {
    code: '6619',
    name: 'Activități auxiliare intermedierilor financiare, exceptând activități de asigurări și fonduri de pensii',
  },
  { code: '6621', name: 'Activități de evaluare a riscului de asigurare și a pagubelor' },
  { code: '6622', name: 'Activități ale agenților și broker-ilor de asigurări' },
  { code: '6629', name: 'Alte activități auxiliare de asigurări și fonduri de pensii' },
  { code: '6630', name: 'Activități de administrare a fondurilor' },
  { code: '6811', name: 'Cumpărarea și vânzarea de bunuri imobiliare proprii' },
  { code: '6812', name: 'Dezvoltare (promovare) imobiliară' },
  {
    code: '6820',
    name: 'Închirierea și subînchirierea bunurilor imobiliare proprii sau închiriate',
  },
  { code: '6831', name: 'Servicii de intermediere a tranzacțiilor imobiliare' },
  {
    code: '6832',
    name: 'Alte activități pentru tranzacții imobiliare pe bază de comision sau contract',
  },
  { code: '6910', name: 'Activități juridice' },
  {
    code: '6920',
    name: 'Activități de contabilitate și audit financiar; consultanță în domeniul fiscal',
  },
  {
    code: '7010',
    name: 'Activități ale direcțiilor(centralelor), birourilor administrative centralizate',
  },
  { code: '7020', name: 'Activități de consultanță în afaceri și management' },
  { code: '7111', name: 'Activități de arhitectură' },
  { code: '7112', name: 'Activități de inginerie și consultanță tehnică legate de acestea' },
  { code: '7120', name: 'Activități de testări și analize tehnice' },
  { code: '7210', name: 'Cercetare-dezvoltare în științe naturale și inginerie' },
  { code: '7220', name: 'Cercetare-dezvoltare în științe sociale și umaniste' },
  { code: '7311', name: 'Activități ale agențiilor de publicitate' },
  { code: '7312', name: 'Servicii de reprezentare media' },
  { code: '7320', name: 'Activități de studiere a pieței și de sondare a opiniei publice' },
  { code: '7330', name: 'Activități în domeniul relațiilor publice și al comunicării' },
  { code: '7411', name: 'Activități de design industrial și vestimentar' },
  { code: '7412', name: 'Design grafic și activități de comunicare vizuală' },
  { code: '7413', name: 'Activități de design de interior' },
  { code: '7414', name: 'Alte activități de design specializat' },
  { code: '7420', name: 'Activități fotografice' },
  { code: '7430', name: 'Activități de traducere scrisă și orală (interpreți)' },
  { code: '7491', name: 'Activități de brokeraj în materie de brevete și servicii de marketing' },
  { code: '7499', name: 'Alte activități profesionale, stiințifice și tehnice n.c.a.' },
  { code: '7500', name: 'Activități veterinare' },
  {
    code: '7711',
    name: 'Activități de închiriere și leasing cu autoturisme și autovehicule rutiere ușoare',
  },
  { code: '7712', name: 'Activități de închiriere și leasing cu autovehicule rutiere grele' },
  {
    code: '7721',
    name: 'Activități de închiriere și leasing cu bunuri recreaționale și echipament sportiv',
  },
  {
    code: '7722',
    name: 'Activități de închiriere și leasing cu alte bunuri personale și gospodărești n.c.a.',
  },
  { code: '7731', name: 'Activități de închiriere și leasing cu mașini și echipamente agricole' },
  {
    code: '7732',
    name: 'Activități de închiriere și leasing cu mașini și echipamente pentru construcții',
  },
  {
    code: '7733',
    name: 'Activități de închiriere și leasing cu mașini și echipamente de birou (inclusiv calculatoare)',
  },
  { code: '7734', name: 'Activități de închiriere și leasing cu echipamente de transport pe apă' },
  { code: '7735', name: 'Activități de închiriere și leasing cu echipamente de transport aerian' },
  {
    code: '7739',
    name: 'Activități de închirierea și leasing cu alte mașini, echipamente și bunuri tangibile n.c.a.',
  },
  {
    code: '7740',
    name: 'Leasing cu bunuri intangibile (cu excepția lucrărilor care fac obiectul drepturilor de autor)',
  },
  {
    code: '7751',
    name: 'Servicii de intermediere pentru închirierea și leasingul autoturismelor, autorulotelor și remorcilor',
  },
  {
    code: '7752',
    name: 'Servicii de intermediere pentru închirierea și leasingul altor bunuri corporale și bunuri intangibile (exceptând financiare)',
  },
  { code: '7810', name: 'Activități ale agențiilor de plasare a forței de muncă' },
  {
    code: '7820',
    name: 'Activități ale agențiilor de plasare temporară a forței de muncă și furnizarea altor resurse umane',
  },
  { code: '7911', name: 'Activități ale agențiilor turistice' },
  { code: '7912', name: 'Activități ale tur-operatorilor' },
  { code: '7990', name: 'Alte servicii de rezervare și asistență turistică' },
  { code: '8001', name: 'Activități de investigații și servicii private de protecție' },
  { code: '8009', name: 'Alte activități de protecție n.c.a.' },
  { code: '8110', name: 'Activități de servicii suport combinate' },
  { code: '8121', name: 'Activități generale de curățenie a clădirilor' },
  { code: '8122', name: 'Activități specializate de curățenie' },
  { code: '8123', name: 'Alte activități de curățenie' },
  { code: '8130', name: 'Activități de înteținere peisagistică' },
  { code: '8210', name: 'Activități de secretariat și servicii suport' },
  { code: '8220', name: 'Activități ale centrelor de intermediere telefonică (call center)' },
  { code: '8230', name: 'Activități de organizare a expozițiilor, târgurilor și congreselor' },
  {
    code: '8240',
    name: 'Activități de intermediere pentru servicii suport pentru întreprinderi n.c.a.',
  },
  {
    code: '8291',
    name: 'Activități ale agențiilor de colectare și a birourilor (oficiilor) de raportare a creditului',
  },
  { code: '8292', name: 'Activități de ambalare' },
  { code: '8299', name: 'Alte activități de servicii suport pentru întreprinderi n.c.a.' },
  { code: '8411', name: 'Activități de administrație publică generală' },
  {
    code: '8412',
    name: 'Reglementarea activităților organismelor care prestează servicii în domeniul îngrijirii sănătății, învățământului, culturii și al altor activități sociale, exceptând protecția socială',
  },
  { code: '8413', name: 'Reglementarea și eficientizarea activităților economice' },
  { code: '8421', name: 'Activități de afaceri externe' },
  { code: '8422', name: 'Activități de apărare națională' },
  { code: '8423', name: 'Activități de justiție' },
  { code: '8424', name: 'Activități de ordine publică și de protecție civilă' },
  { code: '8425', name: 'Activități de luptă împotriva incendiilor și de prevenire a acestora' },
  { code: '8430', name: 'Activități de protecție socială obligatorie' },
  { code: '8510', name: 'Învățământ preșcolar' },
  { code: '8520', name: 'Învățământ primar' },
  { code: '8531', name: 'Învățământ secundar general' },
  { code: '8532', name: 'Învățământ secundar, tehnic sau profesional' },
  { code: '8533', name: 'Învățământ post-secundar, non-universitar' },
  { code: '8540', name: 'Învățământ superior universitar' },
  { code: '8551', name: 'Învățământ în domeniul sportiv și recreațional' },
  {
    code: '8552',
    name: 'Învățământ în domeniul cultural (muzică, teatru, dans, arte plastice, etc.)',
  },
  { code: '8553', name: 'Școli de conducere (pilotaj)' },
  { code: '8559', name: 'Alte forme de învățământ n.c.a.' },
  {
    code: '8561',
    name: 'Activități de intermediere pentru cursuri și tutori (îndrumători, profesori)',
  },
  { code: '8569', name: 'Activități de servicii suport pentru învățământ' },
  { code: '8610', name: 'Activități de asistență spitalicească' },
  { code: '8621', name: 'Activități de asistență medicală generală' },
  { code: '8622', name: 'Activități de asistență medicală specializată' },
  { code: '8623', name: 'Activități de asistență stomatologică' },
  {
    code: '8691',
    name: 'Servicii de diagnostic imagistic și activități ale laboratoarelor medicale',
  },
  { code: '8692', name: 'Transportul pacienților cu ambulanța' },
  { code: '8693', name: 'Activități ale psihologilor și psihoterapeuților, cu excepția medicilor' },
  { code: '8694', name: 'Activități ale infirmierelor și moașelor' },
  { code: '8695', name: 'Activități de fizioterapie' },
  { code: '8696', name: 'Activități de medicină tradițională, complementară și alternativă' },
  {
    code: '8697',
    name: 'Servicii de intermediere pentru servicii medicale, stomatologice și pentru alte servicii referitoare la sănătatea umană',
  },
  { code: '8699', name: 'Alte activități referitoare la sănătatea umană n.c.a.' },
  { code: '8710', name: 'Activități ale centrelor de îngrijire medicală' },
  {
    code: '8720',
    name: 'Activități ale centrelor de recuperare pshică și de dezintoxicare, exclusiv spitale',
  },
  {
    code: '8730',
    name: 'Activități ale căminelor de bătrâni și ale căminelor pentru persoane cu dizabilități aflate în incapacitate de a se îngriji singure',
  },
  { code: '8791', name: 'Activități de intermediere pentru servicii de îngrijire la domiciliu' },
  { code: '8799', name: 'Alte activități de asistență socială, cu cazare n.c.a.' },
  {
    code: '8810',
    name: 'Activități de asistență socială, fără cazare, pentru bătrâni și pentru persoane cu dizabilități aflate în incapacitate de a se îngriji singure',
  },
  { code: '8891', name: 'Activități de îngrijire zilnică pentru copii' },
  { code: '8899', name: 'Alte activități de asistență socială, fără cazare, n.c.a.' },
  { code: '9011', name: 'Activități de creație literară și compoziție muzicală' },
  { code: '9012', name: 'Activități de creație în domeniul artelor vizuale' },
  { code: '9013', name: 'Alte activități de creație artistică' },
  { code: '9020', name: 'Activități de interpretare artistică (spectacole)' },
  { code: '9031', name: 'Activități de gestionare a sălilor și amplasamentelor de spectacole' },
  { code: '9039', name: 'Alte activități suport pentru creație și interpretare artistică' },
  { code: '9111', name: 'Activități ale bibliotecilor' },
  { code: '9112', name: 'Activități ale arhivelor' },
  { code: '9121', name: 'Activități ale muzeelor și colecțiilor' },
  { code: '9122', name: 'Activități ale siturilor și monumentelor istorice' },
  {
    code: '9130',
    name: 'Activități de conservare, restaurare și alte activități suport pentru patrimoniul cultural',
  },
  { code: '9141', name: 'Activități ale grădinilor botanice și zoologice' },
  { code: '9142', name: 'Activități ale rezervațiilor naturale' },
  { code: '9200', name: 'Activități de jocuri de noroc și pariuri' },
  { code: '9311', name: 'Activități ale bazelor sportive' },
  { code: '9312', name: 'Activități ale cluburilor sportive' },
  { code: '9313', name: 'Activități ale centrelor de fitness' },
  { code: '9319', name: 'Alte activități sportive n.c.a' },
  { code: '9321', name: 'Activități ale parcurilor tematice și de distracții' },
  { code: '9329', name: 'Alte activități recreative și distractive n.c.a.' },
  { code: '9411', name: 'Activități ale organizațiilor economice și patronale' },
  { code: '9412', name: 'Activități ale organizațiilor profesionale' },
  { code: '9420', name: 'Activități ale sindicatelor salariaților' },
  { code: '9491', name: 'Activități ale organizațiilor religioase' },
  { code: '9492', name: 'Activități ale organizațiilor politice' },
  { code: '9499', name: 'Activități ale altor organizații n.c.a.' },
  {
    code: '9510',
    name: 'Repararea și întreținerea calculatoarelor și a echipamentelor de comunicații',
  },
  { code: '9521', name: 'Repararea și întreținerea aparatelor electronice de uz casnic' },
  {
    code: '9522',
    name: 'Repararea și întreținerea dispozitivelor de uz gospodăresc și a echipamentelor pentru casă și grădină',
  },
  { code: '9523', name: 'Repararea și întreținerea încălțămintei și a articolelor din piele' },
  { code: '9524', name: 'Repararea și întreținerea mobilei și a furniturilor casnice' },
  { code: '9525', name: 'Repararea și întreținerea ceasurilor și a bijuteriilor' },
  {
    code: '9529',
    name: 'Repararea și întreținerea articolelor de uz personal și gospodăresc n.c.a.',
  },
  { code: '9531', name: 'Repararea și întreținerea autovehiculelor' },
  { code: '9532', name: 'Repararea și întreținerea motocicletelor' },
  {
    code: '9540',
    name: 'Servicii de intermediere pentru repararea și întreținerea calculatoarelor, a articolelor personale și de uz gospodăresc, a autovehiculelor și motocicletelor',
  },
  { code: '9610', name: 'Spălarea și curățarea articolelor textile și a produselor din blană' },
  { code: '9621', name: 'Activități de coafură și frizerie' },
  { code: '9622', name: 'Activități de tratament și înfrumusețare' },
  { code: '9623', name: 'Activități ale centrelor spa, saunelor și bailor de abur' },
  { code: '9630', name: 'Activități de pompe funebre și similare' },
  { code: '9640', name: 'Activități de intermediere pentru servicii personale' },
  { code: '9691', name: 'Activități de servicii personale la domiciliu' },
  { code: '9699', name: 'Alte servicii personale n.c.a.' },
  {
    code: '9700',
    name: 'Activități ale gospodăriilor private în calitate de angajator de personal casnic',
  },
  {
    code: '9810',
    name: 'Activități ale gospodăriilor private de producere de bunuri destinate consumului propriu',
  },
  {
    code: '9820',
    name: 'Activități ale gospodăriilor private de producere de servicii pentru scopuri proprii',
  },
  { code: '9900', name: 'Activități ale organizațiilor și organismelor extrateritoriale' },
];

const caenByCode = new Map(caenClasses.map((entry) => [entry.code, entry.name]));

// The activity name for a class code, or null when the code is not in CAEN Rev. 3.
export function caenClassName(code: string | null | undefined) {
  return code ? (caenByCode.get(code) ?? null) : null;
}
