import type { DocxEditorProps } from '@docx-editor.dev/react';

// The package ships ten languages and Romanian is not one of them; a key left out here shows in
// English. The terms are the ones Word uses in Romanian, since that is where the people
// correcting these documents learned them. `_lang` picks the plural rules ("2 rezultate",
// "20 de rezultate"). Keyboard shortcuts are left to English.
export const editorStrings: NonNullable<DocxEditorProps['i18n']> = {
  _lang: 'ro',
  common: {
    cancel: 'Renunță',
    apply: 'Aplică',
    close: 'Închide',
    comment: 'Comentariu',
    dismiss: 'Ascunde',
  },
  disabledReason: {
    editorNotReady: 'Editorul nu este încă pregătit',
    notWired: 'Acest buton nu este legat de o comandă a editorului',
    viewing: 'Documentul este deschis doar pentru citire',
    trackedOnly: 'Documentul permite modificări doar ca revizii urmărite',
    noDocument: 'Nu este încărcat niciun document',
    noReviewAuthors: 'Documentul nu are autori de revizii',
    suggestingNeedsAuthor:
      'Sugestiile au nevoie de un autor. Setați autorul în configurarea editorului.',
    noContentControl: 'Nu este selectat niciun control de conținut',
    noCopiedFormatting: 'Copiați mai întâi formatarea de undeva',
    noDrawing: 'Nu este selectată nicio imagine',
    drawingLocked: 'Imaginea este blocată',
    commentSelection: 'Selectați un text înainte de a adăuga un comentariu',
    mergeUnsupported: 'Aceste celule nu pot fi unite',
    splitUnsupported: 'Această celulă nu poate fi scindată',
    imageSuggesting: 'Imaginile nu pot fi modificate în modul de sugestii',
    invalidValue: 'Valoarea nu este validă pentru această comandă',
    unavailable: 'Comanda nu este disponibilă',
    bodyOnlySectionBreak: 'Sfârșiturile de secțiune se pun în corpul documentului.',
    bodyOnlyToc: 'Cuprinsul se pune în corpul documentului.',
    bodyOnlyNote: 'Notele de subsol și de final se adaugă din corpul documentului.',
    furnitureOnlyPageField: 'Deschideți un antet sau un subsol pentru a insera numărul paginii.',
    suggestingSectionBreak:
      'Opriți modul de sugestii pentru a insera acest sfârșit de secțiune. El schimbă locul în care începe secțiunea următoare, iar asta nu poate fi o sugestie.',
    tableCellSectionBreak: 'Sfârșiturile de secțiune se pun în afara tabelului.',
    lockedSectionBreak:
      'Secțiunea următoare este într-un control de conținut blocat sau legat, așa că acest sfârșit nu o poate schimba.',
    lockedContentBreak:
      'Textul este blocat de un control de conținut, așa că secțiunea nu poate fi întreruptă aici.',
    nothingToCopyFormatting: 'Selectați un text pentru a-i copia formatarea',
    nothingToPaint: 'Selectați un text pentru a-i aplica formatarea',
  },
  toolbar: {
    ariaLabel: 'Bara de formatare',
    file: 'Fișier',
    format: 'Format',
    insert: 'Inserare',
    review: 'Revizuire',
    open: 'Deschide',
    save: 'Salvează',
    print: 'Imprimă',
    pageSetup: 'Inițializare pagină',
    leftToRight: 'Text de la stânga la dreapta',
    rightToLeft: 'Text de la dreapta la stânga',
    image: 'Imagine',
    table: 'Tabel',
    insertTable: 'Inserează un tabel',
    break: 'Sfârșit',
    insertFootnote: 'Inserează o notă de subsol',
    insertEndnote: 'Inserează o notă de final',
    pageBreak: 'Sfârșit de pagină',
    sectionBreakNextPage: 'Sfârșit de secțiune (pagina următoare)',
    sectionBreakContinuous: 'Sfârșit de secțiune (continuu)',
    tableOfContents: 'Cuprins',
    watermark: 'Inscripționare',
    help: 'Ajutor',
    reportIssue: 'Raportează o problemă',
  },
  toc: {
    refresh: 'Actualizează cuprinsul',
    refreshPageNumbers: 'Actualizează numerele de pagină',
  },
  formattingBar: {
    groups: {
      history: 'Istoric',
      zoom: 'Mărire',
      styles: 'Stiluri',
      font: 'Font',
      textFormatting: 'Formatarea textului',
      script: 'Indice și exponent',
      alignment: 'Aliniere',
      listFormatting: 'Formatarea listelor',
      format: 'Format',
      image: 'Imagine',
      table: 'Tabel',
    },
    undo: 'Anulează',
    undoShortcut: 'Anulează (Ctrl+Z)',
    redo: 'Refă',
    redoShortcut: 'Refă (Ctrl+Y)',
    bold: 'Aldin',
    boldShortcut: 'Aldin (Ctrl+B)',
    italic: 'Cursiv',
    italicShortcut: 'Cursiv (Ctrl+I)',
    underline: 'Subliniat',
    underlineShortcut: 'Subliniat (Ctrl+U)',
    strikethrough: 'Tăiat',
    fontColor: 'Culoarea fontului',
    highlightColor: 'Culoarea de evidențiere a textului',
    insertLink: 'Inserează un link',
    insertLinkShortcut: 'Inserează un link (Ctrl+K)',
    superscript: 'Exponent',
    superscriptShortcut: 'Exponent (Ctrl+Shift+=)',
    subscript: 'Indice',
    subscriptShortcut: 'Indice (Ctrl+=)',
    imageProperties: 'Proprietățile imaginii',
    imagePropertiesShortcut: 'Proprietățile imaginii (text alternativ, bordură)...',
    imageWrap: 'Încadrarea textului',
    altText: 'Text alternativ',
    clearFormatting: 'Șterge formatarea',
    formatPainter: 'Descriptor de formate',
    formatPainterShortcut: 'Descriptor de formate (Ctrl+Alt+C, Ctrl+Alt+V)',
    commentsAndChanges: 'Comentarii și modificări',
    more: 'Mai multe',
    unavailableInPreview: 'Nu este disponibil în această versiune de previzualizare',
    paragraphMarks: 'Arată marcajele de paragraf',
  },
  alignment: {
    alignLeft: 'Aliniere la stânga',
    center: 'La centru',
    alignRight: 'Aliniere la dreapta',
    justify: 'Stânga-dreapta',
  },
  lists: {
    ariaLabel: 'Formatarea listelor',
    typeAriaLabel: 'Tipul listei',
    indentationAriaLabel: 'Indentarea listei',
    bulletList: 'Listă cu marcatori',
    numberedList: 'Listă numerotată',
    decreaseIndent: 'Micșorează indentul',
    increaseIndent: 'Mărește indentul',
  },
  lineSpacing: {
    label: 'Spațiere între rânduri',
    single: 'La un rând',
    double: 'La două rânduri',
    lineSpacingTitle: 'Spațiere între rânduri: {label}',
    blockSpacingRules: 'Spațiere între paragrafe',
    addSpaceBefore: 'Adaugă spațiu înaintea paragrafului',
    removeSpaceBefore: 'Elimină spațiul dinaintea paragrafului',
    addSpaceAfter: 'Adaugă spațiu după paragraf',
    removeSpaceAfter: 'Elimină spațiul de după paragraf',
    options: 'Opțiuni de spațiere între rânduri…',
  },
  styles: {
    selectAriaLabel: 'Alegeți stilul paragrafului',
    normalText: 'Text normal',
    title: 'Titlu',
    subtitle: 'Subtitlu',
    heading1: 'Titlu 1',
    heading2: 'Titlu 2',
    heading3: 'Titlu 3',
  },
  font: {
    selectAriaLabel: 'Alegeți fontul',
    sansSerif: 'Fără serife',
    serif: 'Cu serife',
    monospace: 'Monospațiat',
    documentFonts: 'Fonturile documentului',
    search: 'Caută fonturi',
  },
  fontSize: {
    decrease: 'Micșorează fontul',
    increase: 'Mărește fontul',
    label: 'Dimensiunea fontului',
    listLabel: 'Dimensiuni de font',
  },
  zoom: {
    ariaLabel: 'Mărire: {label}',
    zoomOut: 'Micșorează',
    zoomIn: 'Mărește',
    zoomLevel: 'Nivel de mărire',
    automatic: 'Automat',
    fitWidth: 'Lățimea paginii',
  },
  colorPicker: {
    highlightColors: 'Culori de evidențiere',
    customColor: 'Culoare particularizată',
    noColor: 'Fără culoare',
    automatic: 'Automat',
    themeColors: 'Culorile temei',
    theme: {
      background1: 'Fundal 1',
      text1: 'Text 1',
      background2: 'Fundal 2',
      text2: 'Text 2',
      accent1: 'Accent 1',
      accent2: 'Accent 2',
      accent3: 'Accent 3',
      accent4: 'Accent 4',
      accent5: 'Accent 5',
      accent6: 'Accent 6',
    },
    standardColors: 'Culori standard',
    colors: {
      black: 'Negru',
      darkRed: 'Roșu închis',
      red: 'Roșu',
      orange: 'Portocaliu',
      yellow: 'Galben',
      darkYellow: 'Galben închis',
      green: 'Verde',
      darkGreen: 'Verde închis',
      blue: 'Albastru',
      darkBlue: 'Albastru închis',
      purple: 'Violet',
      white: 'Alb',
      lightGreen: 'Verde deschis',
      lightBlue: 'Albastru deschis',
      darkGray: 'Gri închis',
      cyan: 'Turcoaz',
      darkCyan: 'Turcoaz închis',
      magenta: 'Fucsia',
      darkMagenta: 'Fucsia închis',
      lightGray: 'Gri deschis',
      brightGreen: 'Verde aprins',
    },
    apply: 'Aplică',
  },
  dialogs: {
    imageProperties: {
      title: 'Proprietățile imaginii',
      altText: 'Text alternativ',
      altTextPlaceholder: 'Descrieți imaginea pentru cei care nu o pot vedea...',
      textWrapping: 'Încadrarea textului',
      dimensions: 'Dimensiuni',
      widthLabel: 'Lățime:',
      heightLabel: 'Înălțime:',
      lockAspectRatio: 'Păstrează proporțiile',
    },
    imagePosition: {
      relativeOptions: {
        page: 'Pagină',
        column: 'Coloană',
        margin: 'Margine',
        character: 'Caracter',
        paragraph: 'Paragraf',
        line: 'Rând',
      },
    },
    pageSetup: {
      title: 'Inițializare pagină',
      pageSize: 'DIMENSIUNEA PAGINII',
      sizeLabel: 'Dimensiune',
      custom: 'Particularizată',
      orientation: 'Orientare',
      portrait: 'Portret',
      landscape: 'Vedere',
      margins: 'MARGINI',
      top: 'Sus',
      bottom: 'Jos',
      left: 'Stânga',
      right: 'Dreapta',
      applyTo: 'Se aplică pentru',
      applyToDocument: 'Tot documentul',
      applyToSection: 'Această secțiune',
      pageSizes: {
        letter: 'Letter (215,9 × 279,4 mm)',
        a4: 'A4 (210 × 297 mm)',
        legal: 'Legal (215,9 × 355,6 mm)',
        a3: 'A3 (297 × 420 mm)',
        a5: 'A5 (148 × 210 mm)',
        b5: 'B5 (176 × 250 mm)',
        executive: 'Executive (184,2 × 266,7 mm)',
      },
    },
    footnoteProperties: {
      title: 'Proprietățile notelor de subsol și de final',
      footnotes: 'Note de subsol',
      endnotes: 'Note de final',
      position: 'Poziție',
      numberFormat: 'Format de număr',
      numbering: 'Numerotare',
      footnotePositions: {
        bottomOfPage: 'În partea de jos a paginii',
        belowText: 'Sub text',
      },
      endnotePositions: {
        endOfDocument: 'La sfârșitul documentului',
        endOfSection: 'La sfârșitul secțiunii',
      },
      numberingOptions: {
        continuous: 'Continuă',
        restartSection: 'Reîncepe la fiecare secțiune',
        restartPage: 'Reîncepe la fiecare pagină',
      },
    },
    paragraph: {
      title: 'Paragraf',
      general: 'General',
      alignment: 'Aliniere',
      alignLeft: 'La stânga',
      alignCenter: 'La centru',
      alignRight: 'La dreapta',
      alignJustify: 'Stânga-dreapta',
      indentation: 'Indentare',
      beforeText: 'Înaintea textului',
      afterText: 'După text',
      special: 'Special',
      specialNone: '(fără)',
      specialFirstLine: 'Primul rând',
      specialHanging: 'Agățat',
      by: 'Cu',
      spacing: 'Spațiere',
      spaceBefore: 'Înainte',
      spaceAfter: 'După',
      lineSpacing: 'Spațiere între rânduri',
      ruleMultiple: 'Multiplu',
      ruleAtLeast: 'Cel puțin',
      ruleExactly: 'Exact',
      at: 'La',
      contextualSpacing: 'Fără spațiu între paragrafele cu același stil',
      pagination: 'Paginare',
      keepNext: 'Păstrează cu următorul',
      keepLines: 'Păstrează rândurile împreună',
      widowControl: 'Control rânduri văduve și orfane',
      pageBreakBefore: 'Sfârșit de pagină înainte',
      ok: 'OK',
      cancel: 'Renunță',
      tabStops: 'Tabulatori',
      tabPosition: 'Poziție',
      tabAlignment: 'Aliniere',
      tabLeader: 'Caracter de umplere',
      tabAdd: 'Setează',
      tabClearAll: 'Șterge tot',
      tabRemove: 'Șterge',
      tabNone: 'Fără',
      tabAlignLeft: 'Stânga',
      tabAlignCenter: 'Centru',
      tabAlignRight: 'Dreapta',
      tabAlignDecimal: 'Zecimal',
      tabAlignBar: 'Bară',
      tabLeaderDot: 'Puncte',
      tabLeaderHyphen: 'Linii',
      tabLeaderUnderscore: 'Subliniere',
      tabEmpty: 'Niciun tabulator setat.',
      tabRemoveAt: 'Șterge tabulatorul de la {position} inchi',
      refused: 'Aceste valori nu pot fi aplicate aici.',
      tabMixed: 'Paragrafele selectate au tabulatori diferiți.',
      mixed: 'Diferite',
      notShown: 'Nu se afișează aici',
    },
  },
  comments: {
    unknown: 'Necunoscut',
    addComment: 'Adăugați un comentariu...',
    replyPlaceholder: 'Răspundeți sau menționați pe cineva cu @',
    resolve: 'Rezolvă',
    reopen: 'Redeschide',
  },
  revisions: {
    paragraphMarkInserted: 'A inserat un sfârșit de paragraf',
    paragraphMarksInserted: 'A inserat sfârșituri de paragraf',
    paragraphMarkDeleted: 'A șters un sfârșit de paragraf',
    paragraphMarksDeleted: 'A șters sfârșituri de paragraf',
    paragraphMarkMovedFrom: 'A mutat de aici un sfârșit de paragraf',
    paragraphMarksMovedFrom: 'A mutat de aici sfârșituri de paragraf',
    paragraphMarkMovedTo: 'A mutat aici un sfârșit de paragraf',
    paragraphMarksMovedTo: 'A mutat aici sfârșituri de paragraf',
    runPropertiesChanged: 'A formatat',
    formattingDetails: {
      bold: 'Aldin',
      notBold: 'Fără aldin',
      italic: 'Cursiv',
      notItalic: 'Fără cursiv',
      underline: 'Subliniat',
      strike: 'Tăiat',
      notStrike: 'Netăiat',
      fontFamily: 'Font',
      fontSize: 'Dimensiunea fontului',
      color: 'Culoarea fontului',
      alignment: 'Aliniere',
      leftIndent: 'Indent la stânga',
      rightIndent: 'Indent la dreapta',
      firstLineIndent: 'Indent pentru primul rând',
      hangingIndent: 'Indent agățat',
      spaceBefore: 'Spațiu înainte',
      spaceAfter: 'Spațiu după',
      default: 'Implicit',
      left: 'La stânga',
      center: 'La centru',
      right: 'La dreapta',
      both: 'Stânga-dreapta',
      start: 'Început',
      end: 'Sfârșit',
      none: 'Fără',
      single: 'La un rând',
      double: 'La două rânduri',
      auto: 'Automat',
    },
  },
  contextMenu: {
    ariaLabel: 'Meniu contextual',
    cut: 'Decupează',
    copy: 'Copiază',
    paste: 'Lipește',
    pasteWithoutFormatting: 'Lipește fără formatare',
    copyFormatting: 'Copiază formatarea',
    pasteFormatting: 'Lipește formatarea',
    delete: 'Șterge',
    selectAll: 'Selectează tot',
    editCustomNode: 'Editează {label}',
    removeCustomNode: 'Elimină {label}',
  },
  documentOutline: {
    ariaLabel: 'Schița documentului',
    closeAriaLabel: 'Închide schița',
    closeTitle: 'Închide schița',
    title: 'Schiță',
    noHeadings: 'Nu s-au găsit titluri. Adăugați titluri în document pentru a le vedea aici.',
  },
  navigation: {
    ariaLabel: 'Navigare în document',
    title: 'Navigare',
    openAriaLabel: 'Deschide navigarea',
    openTitle: 'Navigare',
    closeAriaLabel: 'Închide navigarea',
    closeTitle: 'Închide navigarea',
    tabs: {
      headings: 'Titluri',
      find: 'Căutare',
    },
    headings: {
      noHeadings: 'Nu s-au găsit titluri. Adăugați titluri în document pentru a le vedea aici.',
    },
    find: {
      placeholder: 'Caută în document',
      inputAriaLabel: 'Caută în document',
      clearAriaLabel: 'Golește căutarea',
      previousAriaLabel: 'Rezultatul anterior',
      nextAriaLabel: 'Rezultatul următor',
      matchCase: 'Potrivește literele mari și mici',
      wholeWord: 'Doar cuvinte întregi',
      optionsAriaLabel: 'Opțiuni de căutare',
      resultsAriaLabel: 'Rezultatele căutării',
      noResults: 'Niciun rezultat',
      searching: 'Se caută…',
      counter: 'Rezultatul {current} din {total}',
      counterTruncated: 'Rezultatul {current} din {total}+',
      total: '{total, plural, one {# rezultat} few {# rezultate} other {# de rezultate}}',
      totalTruncated: '{total, plural, few {#+ rezultate} other {#+ de rezultate}}',
    },
  },
  viewer: {
    pageIndicator: '{current} din {total}',
  },
  titleBar: {
    untitled: 'Fără titlu',
    documentNameAriaLabel: 'Numele documentului',
    menuBarAriaLabel: 'Bara de meniuri',
  },
  errors: {
    unableToParse: 'Documentul nu a putut fi citit',
    somethingWentWrong: 'Ceva nu a mers',
    errorDescription:
      'A apărut o eroare la afișarea acestei componente. Încercați din nou sau contactați-ne dacă problema persistă.',
    errorLabel: 'Eroare:',
    componentStack: 'Stiva de componente:',
    tryAgain: 'Încearcă din nou',
    showDetails: 'Arată detaliile',
    hideDetails: 'Ascunde detaliile',
  },
  table: {
    insertRowAbove: 'Inserează un rând deasupra',
    insertRowBelow: 'Inserează un rând dedesubt',
    insertColumnLeft: 'Inserează o coloană la stânga',
    insertColumnRight: 'Inserează o coloană la dreapta',
    deleteRow: 'Șterge rândul',
    deleteColumn: 'Șterge coloana',
    deleteTable: 'Șterge tabelul',
    selectTable: 'Selectează tot tabelul',
    mergeCells: 'Unește celulele',
    splitCell: 'Scindează celula',
    editingTools: 'Instrumente pentru tabel',
    label: 'Tabel:',
    cellFillColor: 'Culoarea de umplere a celulei',
    borderColor: 'Culoarea bordurii',
    borderWidth: 'Grosimea bordurii',
    clearCellFill: 'Elimină umplerea celulei',
    borderStyles: {
      single: 'Continuă',
      dashed: 'Întreruptă',
      dotted: 'Punctată',
      double: 'Dublă',
      triple: 'Triplă',
      thick: 'Groasă',
    },
    borderWidths: {
      halfPt: '0,5 pt',
      onePt: '1 pt',
      oneHalfPt: '1,5 pt',
      twoPt: '2 pt',
      threePt: '3 pt',
    },
    borders: {
      all: 'Toate bordurile',
      outside: 'Borduri exterioare',
      inside: 'Borduri interioare',
      none: 'Fără borduri',
      top: 'Bordură sus',
      bottom: 'Bordură jos',
      left: 'Bordură la stânga',
      right: 'Bordură la dreapta',
      styleAriaLabel: 'Stilul bordurii',
      tooltip: 'Borduri',
    },
    moreOptions: 'Mai multe opțiuni pentru tabel',
  },
  tableAdvanced: {
    verticalAlignment: 'Aliniere verticală',
    top: 'Sus',
    middle: 'La mijloc',
    bottom: 'Jos',
    toggleNoWrap: 'Comută textul pe un singur rând',
    toggleHeaderRow: 'Comută rândul de antet',
    distributeColumns: 'Distribuie coloanele uniform',
    autoFit: 'Potrivire automată la conținut',
    tableProperties: 'Proprietățile tabelului...',
    tableAlignment: 'Alinierea tabelului',
    alignTableLeft: 'Aliniază tabelul la stânga',
    alignTableCenter: 'Aliniază tabelul la centru',
    alignTableRight: 'Aliniază tabelul la dreapta',
  },
  imageTransform: {
    tooltip: 'Transformă',
    rotateClockwise: 'Rotește spre dreapta',
    rotateCounterClockwise: 'Rotește spre stânga',
    flipHorizontal: 'Răstoarnă orizontal',
    flipVertical: 'Răstoarnă vertical',
  },
  imageWrap: {
    inline: 'În linie cu textul',
    square: 'Pătrat',
    tight: 'Strâns',
    through: 'Printre',
    floatLeft: 'Pătrat, la stânga',
    floatRight: 'Pătrat, la dreapta',
    topAndBottom: 'Sus și jos',
    behindText: 'În spatele textului',
    inFrontOfText: 'În fața textului',
    tooltipPrefix: 'Încadrare: {label}',
    targets: {
      inline: 'În linie cu textul',
      square: 'Pătrat',
      squareLeft: 'Pătrat, la stânga',
      squareRight: 'Pătrat, la dreapta',
      tight: 'Strâns',
      through: 'Printre',
      topAndBottom: 'Sus și jos',
      behind: 'În spatele textului',
      inFront: 'În fața textului',
    },
    menu: {
      inLineWithText: 'În linie cu textul',
      squareLeft: 'Pătrat, la stânga',
      squareRight: 'Pătrat, la dreapta',
      ariaLabel: 'Opțiuni de așezare a imaginii',
    },
  },
  imageInsert: {
    errors: {
      emptyFile: 'Fișierul ales este gol.',
      invalidSignature: 'Fișierul nu este o imagine PNG, JPEG sau GIF acceptată.',
      unsupportedFormat: 'Acest format de imagine nu poate fi inserat.',
      oversize: 'Imaginea depășește dimensiunea maximă permisă.',
      refused: 'Imaginea nu a putut fi inserată.',
    },
  },
  imageProperties: {
    hyperlink: 'Link',
    crop: 'Trunchiere',
    cropLeft: 'Stânga (%)',
    cropTop: 'Sus (%)',
    cropRight: 'Dreapta (%)',
    cropBottom: 'Jos (%)',
    resetNaturalSize: 'Revino la dimensiunea originală',
    nonPictureHint:
      'Trunchierea și revenirea la dimensiunea originală sunt disponibile doar pentru imagini.',
    errors: {
      invalidDimensions: 'Introduceți valori pozitive pentru lățime și înălțime.',
      invalidCrop: 'Valorile de trunchiere trebuie să fie procente între 0 și 100.',
      invalidPosition: 'Introduceți valori valide pentru poziția orizontală și cea verticală.',
      refused: 'Aceste proprietăți nu au putut fi aplicate.',
    },
    position: 'Poziție',
    positionUnavailable: 'Poziția este disponibilă doar pentru imaginile flotante.',
    positionLocked: 'Acest desen nu poate fi mutat.',
    horizontalOffset: 'Decalaj orizontal',
    verticalOffset: 'Decalaj vertical',
    relativeToHorizontal: 'Față de (orizontal)',
    relativeToVertical: 'Față de (vertical)',
  },
  imageAltText: {
    panelTitle: 'Text alternativ',
    title: 'Titlu',
    description: 'Descriere',
  },
  editor: {
    showDocumentOutline: 'Arată schița documentului',
    linkCopied: 'Linkul a fost copiat',
    fontSubstitutionNotice:
      'Unele fonturi din acest document nu sunt disponibile, așa că se afișează înlocuitori: {fonts}',
  },
  hyperlinkPopup: {
    displayTextPlaceholder: 'Textul afișat',
    urlLabel: 'Adresă',
    copyLink: 'Copiază linkul',
    editLink: 'Editează linkul',
    removeLink: 'Elimină linkul',
    openLink: 'Deschide linkul',
    apply: 'Aplică',
    cancel: 'Renunță',
    insertTitle: 'Inserează un link',
    editTitle: 'Editează linkul',
    inertTarget: 'Linkul duce undeva unde editorul nu îl deschide',
    bookmarkTarget: 'Duce la un loc din acest document',
    refused: 'Linkul nu a putut fi aplicat. Verificați adresa și încercați din nou.',
  },
  equationPopup: {
    title: 'Editează ecuația',
    inputLabel: 'Format liniar',
    placeholder: 'Introduceți o ecuație',
    apply: 'Aplică',
    delete: 'Șterge',
    refused: 'Ecuația nu a putut fi aplicată. Verificați sintaxa și încercați din nou.',
  },
  contentControl: {
    group: 'Controale de conținut',
    showAll: 'Arată marginile controalelor de conținut',
    formFill: 'Mod de completare a formularului',
    inspector: 'Proprietățile controlului de conținut',
    remove: 'Elimină controlul de conținut',
    inspectorPanel: {
      title: 'Control de conținut',
      alias: 'Titlu',
      tag: 'Etichetă',
      type: 'Tip',
      lock: 'Blocare',
      placeholder: 'Text substituent',
      bound: 'Legat la date',
      yes: 'Da',
      no: 'Nu',
      boundNote: 'Controlul este legat la date externe. Editarea este refuzată.',
      lockedNote: 'Conținutul acestui control este blocat la editare.',
    },
    types: {
      richText: 'Text îmbogățit',
      plainText: 'Text simplu',
      checkbox: 'Casetă de selectare',
      dropdown: 'Listă verticală',
      comboBox: 'Casetă combo',
      date: 'Dată',
      picture: 'Imagine',
      buildingBlockGallery: 'Galerie de blocuri componente',
      repeatingSection: 'Secțiune repetitivă',
    },
    gallery: {
      empty: 'Documentul nu are blocuri componente pentru această galerie.',
    },
    lock: {
      unlocked: 'Deblocat',
      sdtLocked: 'Control de conținut blocat',
      contentLocked: 'Conținut blocat',
      sdtContentLocked: 'Control de conținut și conținut blocate',
    },
    calendar: {
      today: 'Astăzi',
      previousMonth: 'Luna anterioară',
      nextMonth: 'Luna următoare',
      month: 'Lună',
      year: 'An',
    },
  },
  headerFooter: {
    chromeAriaLabel: 'Editarea antetului și a subsolului',
    header: 'Antet',
    footer: 'Subsol',
    firstPageHeader: 'Antetul primei pagini',
    firstPageFooter: 'Subsolul primei pagini',
    evenPageHeader: 'Antetul paginilor pare',
    evenPageFooter: 'Subsolul paginilor pare',
    sameAsPrevious: 'La fel ca anteriorul',
    sameAsPreviousHint: 'Modificările se aplică și paginilor din secțiunea precedentă.',
    options: 'Opțiuni',
    differentFirstPage: 'Prima pagină diferită',
    differentOddEven: 'Pagini pare și impare diferite',
    differentOddEvenHint: 'Se aplică întregului document.',
    linkToPrevious: 'Leagă la anteriorul',
    unlinkFromPrevious: 'Dezleagă de anteriorul',
    headerDistance: 'Distanța antetului față de margine',
    footerDistance: 'Distanța subsolului față de margine',
    removeHeader: 'Elimină antetul',
    removeFooter: 'Elimină subsolul',
    insertPageNumber: 'Inserează numărul paginii curente',
    insertTotalPages: 'Inserează numărul total de pagini',
    insertSectionPages: 'Inserează numărul de pagini al secțiunii',
    insertPageXofY: 'Inserează „pagina X din Y”',
  },
  image: {
    unsupportedFormat: 'Format de imagine neacceptat ({format})',
    nonPictureGraphic: 'Element grafic neacceptat ({kind})',
    missingResource: 'Imagine lipsă',
    externalResource: 'Imaginea externă nu a fost încărcată',
    invalidResource: 'Imagine nevalidă',
    contentMismatch: 'Conținutul imaginii nu corespunde tipului ei',
    decodeFailed: 'Imaginea nu a putut fi decodificată',
    resourceLimit: 'Imaginea depășește limitele de dimensiune',
    pendingResource: 'Se încarcă imaginea',
  },
  imageOverlay: {
    selection: 'Imaginea selectată',
    handle: {
      n: 'Redimensionează de la marginea de sus',
      ne: 'Redimensionează din colțul din dreapta sus',
      e: 'Redimensionează de la marginea din dreapta',
      se: 'Redimensionează din colțul din dreapta jos',
      s: 'Redimensionează de la marginea de jos',
      sw: 'Redimensionează din colțul din stânga jos',
      w: 'Redimensionează de la marginea din stânga',
      nw: 'Redimensionează din colțul din stânga sus',
    },
  },
  ruler: {
    horizontal: 'Riglă orizontală',
    vertical: 'Riglă verticală',
    firstLineIndent: 'Indent pentru primul rând',
    hangingIndent: 'Indent agățat',
    leftIndent: 'Indent la stânga',
    rightIndent: 'Indent la dreapta',
    topMargin: 'Marginea de sus',
    bottomMargin: 'Marginea de jos',
  },
  loading: {
    label: 'Se încarcă',
  },
  notes: {
    delete: 'Șterge nota',
    convertToEndnote: 'Transformă în notă de final',
    convertToFootnote: 'Transformă în notă de subsol',
    scope: 'Se aplică pentru',
    scopeDocument: 'Tot documentul',
    scopeSection: 'Această secțiune',
    previewFallback: 'Notă de subsol',
    chromeAriaLabel: 'Editarea notei',
    footnoteKind: 'Nota de subsol',
    endnoteKind: 'Nota de final',
    convertAllFootnotes: 'Transformă toate notele de subsol în note de final',
    convertAllEndnotes: 'Transformă toate notele de final în note de subsol',
    inheritedValue: '(moștenit)',
  },
  reviewers: {
    label: 'Revizori',
    markupOptions: 'Opțiuni de marcaj',
    all: 'Toți',
  },
  editingMode: {
    label: 'Mod de editare',
    editing: 'Editare',
    editingHint: 'Modificați documentul direct',
    suggesting: 'Sugestii',
    suggestingHint: 'Modificările devin sugestii',
    viewing: 'Vizualizare',
    viewingHint: 'Doar citire, fără modificări',
  },
  collaboration: {
    participants: 'Persoane în acest document',
    moreParticipants:
      '{count, plural, one {încă # persoană} few {încă # persoane} other {încă # de persoane}}',
  },
  review: {
    displayForReview: 'Afișare pentru revizuire',
    simpleMarkup: 'Marcaj simplu',
    allMarkup: 'Tot marcajul',
    noMarkup: 'Fără marcaj',
    original: 'Original',
    previousChange: 'Modificarea anterioară',
    nextChange: 'Modificarea următoare',
    acceptAllChanges: 'Acceptă toate modificările afișate',
    rejectAllChanges: 'Respinge toate modificările afișate',
    protectDocument: 'Protejează documentul pentru formulare',
    ariaLabel: 'Revizuire',
    empty: 'Nicio modificare și niciun comentariu',
    accept: 'Acceptă',
    reject: 'Respinge',
    deleteComment: 'Șterge comentariul',
    discardChange: 'Renunță la modificare',
    reply: 'Răspunde',
    inserted: 'Adăugat',
    deleted: 'Șters',
    movedFrom: 'Mutat de aici',
    movedTo: 'Mutat aici',
    structural: 'A schimbat structura documentului',
    replyRefused: 'Răspunsul nu a putut fi publicat',
    showPane: 'Arată comentariile',
    resolved: 'Rezolvat',
    showResolvedComment: 'Arată comentariul rezolvat',
    replaced: 'Înlocuit',
    replacedWith: 'cu',
    commentRefused: 'Comentariul nu a putut fi adăugat',
  },
  textFormField: {
    title: 'Opțiunile câmpului de formular text',
    defaultText: 'Text implicit',
    apply: 'OK',
    cancel: 'Renunță',
    unavailable: 'Acest câmp nu poate fi schimbat.',
    edit: 'Editează câmpul…',
    type: 'Tip',
    regular: 'Text obișnuit',
    number: 'Număr',
    date: 'Dată',
    preservedType: 'Tip de câmp păstrat',
    maxLength: 'Lungime maximă (0 = nelimitată)',
    format: 'Format',
    noFormat: 'Fără format',
    enabled: 'Completare activată',
    invalidOptions: 'Verificați valoarea implicită, tipul, formatul și lungimea maximă.',
    invalidTitle: 'Valoare de câmp nevalidă',
    invalidNumber: 'Este nevoie de un număr valid. Câmpul va fi golit.',
    invalidDate: 'Este nevoie de o dată validă. Câmpul va fi golit.',
    invalidValue: 'Introduceți o valoare validă înainte de a părăsi câmpul.',
    selected:
      'Tot câmpul este selectat. Ce tastați îl înlocuiește când formularul nu este protejat.',
    editing: 'Cursorul este într-un câmp de formular text.',
    uppercase: 'Majuscule',
    lowercase: 'Minuscule',
    firstCapital: 'Prima literă mare',
    titleCase: 'Fiecare cuvânt cu majusculă',
  },
};
